# Generated by Django 5.2.6 on 2026-04-02 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsPac',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_pac', models.CharField(blank=True, help_text='Numéro du détail PAC (peut être dupliqué pour les amendements)', max_length=50, null=True)),
                ('libelle', models.CharField(blank=True, help_text='Libellé du détail', max_length=500, null=True)),
                ('periode_de_realisation', models.DateField(blank=True, help_text='Période de réalisation', null=True)),
            ],
            options={
                'verbose_name': 'Détail PAC',
                'verbose_name_plural': 'Détails PAC',
                'db_table': 'details_pac',
            },
        ),
        migrations.CreateModel(
            name='Pac',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création du PAC')),
                ('is_validated', models.BooleanField(default=False, help_text='Indique que tous les détails et traitements sont renseignés. Permet la création des suivis.')),
                ('validated_at', models.DateTimeField(blank=True, help_text='Date de validation des détails et traitements', null=True)),
                ('raison_amendement', models.TextField(blank=True, help_text='Raison ou motif de la création de cet amendement', null=True)),
            ],
            options={
                'verbose_name': 'PAC',
                'verbose_name_plural': 'PACs',
                'db_table': 'pac',
            },
        ),
        migrations.CreateModel(
            name='PacSuivi',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resultat', models.TextField(blank=True, null=True)),
                ('date_mise_en_oeuvre_effective', models.DateField(blank=True, null=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suivi PAC',
                'verbose_name_plural': 'Suivis PAC',
                'db_table': 'suivi',
            },
        ),
        migrations.CreateModel(
            name='TraitementPac',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('delai_realisation', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Traitement PAC',
                'verbose_name_plural': 'Traitements PAC',
                'db_table': 'traitement',
            },
        ),
    ]
