# Generated by Django 5.2.6 on 2025-09-29 10:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pac',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_pac', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=500)),
                ('periode_de_realisation', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacs', to='parametre.categorie')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacs_crees', to=settings.AUTH_USER_MODEL)),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacs', to='parametre.nature')),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacs', to='parametre.processus')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacs', to='parametre.source')),
            ],
            options={
                'verbose_name': 'PAC',
                'verbose_name_plural': 'PACs',
                'db_table': 'pac',
            },
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('delai_realisation', models.DateField()),
                ('pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='pac.pac')),
                ('preuve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements', to='parametre.preuve')),
                ('responsable_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traitements_responsables', to='parametre.direction')),
                ('responsable_sous_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traitements_responsables', to='parametre.sousdirection')),
                ('type_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='parametre.actiontype')),
            ],
            options={
                'verbose_name': 'Traitement',
                'verbose_name_plural': 'Traitements',
                'db_table': 'traitement',
            },
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resultat', models.TextField(blank=True, null=True)),
                ('date_mise_en_oeuvre_effective', models.DateField(blank=True, null=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appreciation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='parametre.appreciation')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_crees', to=settings.AUTH_USER_MODEL)),
                ('etat_mise_en_oeuvre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='parametre.etatmiseenoeuvre')),
                ('preuve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis', to='parametre.preuve')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis', to='parametre.statut')),
                ('traitement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='pac.traitement')),
            ],
            options={
                'verbose_name': 'Suivi',
                'verbose_name_plural': 'Suivis',
                'db_table': 'suivi',
            },
        ),
    ]
