# Generated by Django 5.2.6 on 2025-10-09 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0001_initial'),
        ('parametre', '0014_dysfonctionnementrecommandation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pac',
            name='dysfonctionnement_recommandation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacs', to='parametre.dysfonctionnementrecommandation'),
        ),
    ]
