# Generated by Django 5.2.6 on 2026-04-02 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pac', '0001_initial'),
        ('parametre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detailspac',
            name='categorie',
            field=models.ForeignKey(blank=True, help_text='Catégorie du détail', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details_pacs', to='parametre.categorie'),
        ),
        migrations.AddField(
            model_name='detailspac',
            name='dysfonctionnement_recommandation',
            field=models.ForeignKey(blank=True, help_text='Dysfonctionnement ou recommandation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details_pacs', to='parametre.dysfonctionnementrecommandation'),
        ),
        migrations.AddField(
            model_name='detailspac',
            name='nature',
            field=models.ForeignKey(blank=True, help_text='Nature du détail', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details_pacs', to='parametre.nature'),
        ),
        migrations.AddField(
            model_name='detailspac',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Source du détail', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details_pacs', to='parametre.source'),
        ),
        migrations.AddField(
            model_name='pac',
            name='annee',
            field=models.ForeignKey(blank=True, help_text='Année associée au PAC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacs', to='parametre.annee'),
        ),
        migrations.AddField(
            model_name='pac',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacs_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pac',
            name='initial_ref',
            field=models.ForeignKey(blank=True, help_text='Référence au PAC initial (pour les amendements)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amendements', to='pac.pac'),
        ),
        migrations.AddField(
            model_name='pac',
            name='processus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacs', to='parametre.processus'),
        ),
        migrations.AddField(
            model_name='pac',
            name='type_tableau',
            field=models.ForeignKey(blank=True, help_text='Version associée au PAC (Initial, Amendement, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacs', to='parametre.versions'),
        ),
        migrations.AddField(
            model_name='pac',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a validé le PAC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacs_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detailspac',
            name='pac',
            field=models.ForeignKey(blank=True, help_text='PAC associé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pac.pac'),
        ),
        migrations.AddField(
            model_name='pacsuivi',
            name='appreciation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='parametre.appreciation'),
        ),
        migrations.AddField(
            model_name='pacsuivi',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pacsuivi',
            name='etat_mise_en_oeuvre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='parametre.etatmiseenoeuvre'),
        ),
        migrations.AddField(
            model_name='pacsuivi',
            name='preuve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis', to='parametre.preuve'),
        ),
        migrations.AddField(
            model_name='pacsuivi',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis', to='parametre.statut'),
        ),
        migrations.AddField(
            model_name='traitementpac',
            name='details_pac',
            field=models.OneToOneField(blank=True, help_text='Détails PAC associé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traitement', to='pac.detailspac'),
        ),
        migrations.AddField(
            model_name='traitementpac',
            name='preuve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements', to='parametre.preuve'),
        ),
        migrations.AddField(
            model_name='traitementpac',
            name='responsable_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traitements_responsables', to='parametre.direction'),
        ),
        migrations.AddField(
            model_name='traitementpac',
            name='responsable_sous_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traitements_responsables', to='parametre.sousdirection'),
        ),
        migrations.AddField(
            model_name='traitementpac',
            name='responsables_directions',
            field=models.ManyToManyField(blank=True, related_name='traitements_responsables_m2m', to='parametre.direction'),
        ),
        migrations.AddField(
            model_name='traitementpac',
            name='responsables_sous_directions',
            field=models.ManyToManyField(blank=True, related_name='traitements_responsables_sous_m2m', to='parametre.sousdirection'),
        ),
        migrations.AddField(
            model_name='traitementpac',
            name='type_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='parametre.actiontype'),
        ),
        migrations.AddField(
            model_name='pacsuivi',
            name='traitement',
            field=models.OneToOneField(blank=True, help_text='Traitement PAC associé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivi', to='pac.traitementpac'),
        ),
        migrations.AddConstraint(
            model_name='pac',
            constraint=models.UniqueConstraint(fields=('processus', 'annee', 'type_tableau'), name='unique_pac_per_processus_annee_type_tableau'),
        ),
    ]
