# Generated by Django 5.2.6 on 2025-10-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0002_pac_dysfonctionnement_recommandation'),
        ('parametre', '0014_dysfonctionnementrecommandation'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='responsables_directions',
            field=models.ManyToManyField(blank=True, related_name='traitements_responsables_m2m', to='parametre.direction'),
        ),
        migrations.AddField(
            model_name='traitement',
            name='responsables_sous_directions',
            field=models.ManyToManyField(blank=True, related_name='traitements_responsables_sous_m2m', to='parametre.sousdirection'),
        ),
    ]
