# Generated by Django migrations for making PAC fields optional

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0003_add_m2m_responsables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pac',
            name='libelle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pac',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacs', to='parametre.categorie'),
        ),
        migrations.AlterField(
            model_name='pac',
            name='nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacs', to='parametre.nature'),
        ),
        migrations.AlterField(
            model_name='pac',
            name='periode_de_realisation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pac',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacs', to='parametre.source'),
        ),
    ]

