# Generated by Django 5.2.6 on 2025-09-26 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0004_delete_processus'),
        ('parametre', '0002_add_processus_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='responsable_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traitements_responsables', to='parametre.direction'),
        ),
        migrations.AddField(
            model_name='traitement',
            name='responsable_sous_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traitements_responsables', to='parametre.sousdirection'),
        ),
    ]
