# Generated by Django 5.2.6 on 2025-10-27 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0004_make_pac_fields_optional'),
        ('parametre', '0031_dashboardnotificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitement',
            name='delai_realisation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='type_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='parametre.actiontype'),
        ),
    ]
