# Generated by Django 5.2.6 on 2025-10-28 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0005_make_traitement_fields_optional'),
        ('parametre', '0032_annee_typetableaupac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanActionConformite',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_validated', models.BooleanField(default=False, help_text='Indique si le plan est validé')),
                ('date_validation', models.DateTimeField(blank=True, help_text='Date de validation du plan', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_action_conformite', to='parametre.annee')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_action_conformite_crees', to=settings.AUTH_USER_MODEL)),
                ('initial_ref', models.ForeignKey(blank=True, help_text='Référence au plan initial (pour les révisions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='pac.planactionconformite')),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_action_conformite', to='parametre.processus')),
                ('type_tableau_pac', models.ForeignKey(help_text='Type de tableau PAC', on_delete=django.db.models.deletion.CASCADE, related_name='plans_action_conformite', to='parametre.typetableaupac')),
                ('valide_par', models.ForeignKey(blank=True, help_text='Utilisateur qui a validé le plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_action_conformite_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Plan d'Action de Conformité",
                'verbose_name_plural': "Plans d'Action de Conformité",
                'db_table': 'plan_action_conformite',
                'ordering': ['-annee__annee', 'processus__numero_processus', 'type_tableau_pac__code'],
                'constraints': [models.UniqueConstraint(fields=('annee', 'processus', 'type_tableau_pac'), name='uniq_plan_per_annee_processus_type')],
            },
        ),
    ]
