# Generated by Django 5.2.6 on 2025-09-29 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0005_traitement_responsable_direction_and_more'),
        ('parametre', '0003_media_fichier_alter_media_url_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivi',
            name='date_cloture',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suivi',
            name='date_mise_en_oeuvre_effective',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suivi',
            name='preuve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis', to='parametre.preuve'),
        ),
        migrations.AddField(
            model_name='suivi',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis', to='parametre.statut'),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='preuve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements', to='parametre.preuve'),
        ),
    ]
