# Generated by Django 5.2.6 on 2025-10-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0006_planactionconformite'),
    ]

    operations = [
        migrations.AddField(
            model_name='planactionconformite',
            name='numero_pac',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
