# Generated by Django 5.2.6 on 2025-10-30 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0007_planactionconformite_numero_pac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pac',
            name='numero_pac',
        ),
    ]
