# Generated by Django 5.2.6 on 2025-10-30 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0008_remove_numero_pac_from_pac'),
    ]

    operations = [
        migrations.AddField(
            model_name='pac',
            name='plan_conformite',
            field=models.ForeignKey(blank=True, help_text="Plan d'Action de Conformité auquel appartient ce PAC", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacs', to='pac.planactionconformite'),
        ),
    ]
