# Generated by Django 5.2.6 on 2025-10-30 09:14

import django.db.models.deletion
from django.db import migrations, models


def generate_numero_pac_for_existing(apps, schema_editor):
    """Générer des numéros PAC pour les enregistrements existants"""
    Pac = apps.get_model('pac', 'Pac')
    for index, pac in enumerate(Pac.objects.all(), start=1):
        pac.numero_pac = f"PAC{index:04d}"
        pac.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0009_add_plan_conformite_fk_to_pac'),
        ('parametre', '0033_remove_annee_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pac',
            name='plan_conformite',
        ),
        migrations.RemoveField(
            model_name='planactionconformite',
            name='numero_pac',
        ),
        migrations.AddField(
            model_name='pac',
            name='numero_pac',
            field=models.CharField(blank=True, default='', max_length=50),  # Temporairement sans unique
        ),
        migrations.RunPython(generate_numero_pac_for_existing, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pac',
            name='numero_pac',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),  # Ajouter unique après
        ),
        migrations.AlterField(
            model_name='planactionconformite',
            name='type_tableau_pac',
            field=models.ForeignKey(help_text='Type de tableau PAC', on_delete=django.db.models.deletion.CASCADE, related_name='plans_action_conformite', to='parametre.typetableau'),
        ),
    ]
