# Generated by Django 5.2.6 on 2025-10-30 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0010_remove_pac_plan_conformite_and_more'),
        ('parametre', '0035_add_annee_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='pac',
            name='annee',
            field=models.ForeignKey(blank=True, help_text='Année associée au PAC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacs', to='parametre.annee'),
        ),
        migrations.AddField(
            model_name='pac',
            name='type_tableau',
            field=models.ForeignKey(blank=True, help_text='Type de tableau associé au PAC (Initial, Amendement, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacs', to='parametre.typetableau'),
        ),
        migrations.AlterField(
            model_name='pac',
            name='numero_pac',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='PlanActionConformite',
        ),
    ]
