# Generated by Django 5.2.6 on 2025-10-31 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0011_add_annee_and_type_tableau_to_pac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pac',
            name='date_validation',
            field=models.DateTimeField(blank=True, help_text='Date de validation du PAC', null=True),
        ),
        migrations.AddField(
            model_name='pac',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='Indique si le PAC est validé (verrouille les champs PAC et Traitement)'),
        ),
        migrations.AddField(
            model_name='pac',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a validé le PAC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacs_valides', to=settings.AUTH_USER_MODEL),
        ),
    ]
