# Generated by Django 5.2.6 on 2025-10-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0012_add_validation_fields_to_pac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pac',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='pac',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pac',
            name='date_validation',
        ),
        migrations.RemoveField(
            model_name='pac',
            name='dysfonctionnement_recommandation',
        ),
        migrations.RemoveField(
            model_name='pac',
            name='is_validated',
        ),
        migrations.RemoveField(
            model_name='pac',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='pac',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='pac',
            name='periode_de_realisation',
        ),
        migrations.RemoveField(
            model_name='pac',
            name='source',
        ),
        migrations.RemoveField(
            model_name='pac',
            name='updated_at',
        ),
    ]
