# Generated by Django 5.2.6 on 2025-10-31 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0013_remove_pac_categorie_remove_pac_created_at_and_more'),
        ('parametre', '0035_add_annee_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsPac',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, help_text='Libellé du détail', max_length=500, null=True)),
                ('periode_de_realisation', models.DateField(blank=True, help_text='Période de réalisation', null=True)),
                ('categorie', models.ForeignKey(blank=True, help_text='Catégorie du détail', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details_pacs', to='parametre.categorie')),
                ('dysfonctionnement_recommandation', models.ForeignKey(blank=True, help_text='Dysfonctionnement ou recommandation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details_pacs', to='parametre.dysfonctionnementrecommandation')),
                ('nature', models.ForeignKey(blank=True, help_text='Nature du détail', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details_pacs', to='parametre.nature')),
                ('pac', models.ForeignKey(help_text='PAC associé', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pac.pac')),
                ('source', models.ForeignKey(blank=True, help_text='Source du détail', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details_pacs', to='parametre.source')),
            ],
            options={
                'verbose_name': 'Détail PAC',
                'verbose_name_plural': 'Détails PAC',
                'db_table': 'details_pac',
            },
        ),
    ]
