# Generated by Django 5.2.6 on 2025-10-31 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0014_detailspac'),
        ('parametre', '0035_add_annee_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Traitement',
            new_name='TraitementPac',
        ),
        migrations.AlterModelOptions(
            name='traitementpac',
            options={'verbose_name': 'Traitement PAC', 'verbose_name_plural': 'Traitements PAC'},
        ),
        migrations.RemoveField(
            model_name='detailspac',
            name='pac',
        ),
        migrations.AddField(
            model_name='detailspac',
            name='traitement',
            field=models.ForeignKey(blank=True, help_text='Traitement PAC associé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pac.traitementpac'),
        ),
    ]
