# Generated by Django 5.2.6 on 2025-10-31 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0015_rename_traitement_traitementpac_and_more'),
        ('parametre', '0035_add_annee_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suivi',
            new_name='PacSuivi',
        ),
        migrations.AlterModelOptions(
            name='pacsuivi',
            options={'verbose_name': 'Suivi PAC', 'verbose_name_plural': 'Suivis PAC'},
        ),
        migrations.RemoveField(
            model_name='pacsuivi',
            name='traitement',
        ),
        migrations.AddField(
            model_name='pacsuivi',
            name='details_pac',
            field=models.ForeignKey(blank=True, help_text='Détails PAC associé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='pac.detailspac'),
        ),
    ]
