# Generated by Django 5.2.6 on 2025-10-31 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0016_pacsuivi_delete_suivi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailspac',
            name='traitement',
        ),
        migrations.RemoveField(
            model_name='pacsuivi',
            name='details_pac',
        ),
        migrations.RemoveField(
            model_name='traitementpac',
            name='pac',
        ),
        migrations.AddField(
            model_name='detailspac',
            name='pac',
            field=models.ForeignKey(blank=True, help_text='PAC associé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pac.pac'),
        ),
        migrations.AddField(
            model_name='pacsuivi',
            name='traitement',
            field=models.ForeignKey(blank=True, help_text='Traitement PAC associé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='pac.traitementpac'),
        ),
        migrations.AddField(
            model_name='traitementpac',
            name='details_pac',
            field=models.ForeignKey(blank=True, help_text='Détails PAC associé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='pac.detailspac'),
        ),
    ]
