# Generated by Django 5.2.6 on 2025-10-31 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0017_remove_detailspac_traitement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacsuivi',
            name='traitement',
            field=models.OneToOneField(blank=True, help_text='Traitement PAC associé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivi', to='pac.traitementpac'),
        ),
        migrations.AlterField(
            model_name='traitementpac',
            name='details_pac',
            field=models.OneToOneField(blank=True, help_text='Détails PAC associé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traitement', to='pac.detailspac'),
        ),
    ]
