# Generated by Django 5.2.6 on 2025-10-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0018_change_foreignkey_to_onetoone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pac',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='Indique que tous les détails et traitements sont renseignés. Permet la création des suivis.'),
        ),
        migrations.AddField(
            model_name='pac',
            name='validated_at',
            field=models.DateTimeField(blank=True, help_text='Date de validation des détails et traitements', null=True),
        ),
    ]
