# Generated by Django 5.2.6 on 2025-10-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0019_add_is_validated_to_pac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pac',
            name='numero_pac',
        ),
        migrations.AddField(
            model_name='detailspac',
            name='numero_pac',
            field=models.CharField(blank=True, help_text='Numéro unique du détail PAC', max_length=50, null=True, unique=True),
        ),
    ]
