# Generated by Django 5.2.6 on 2025-10-31 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0020_move_numero_pac_to_details'),
        ('parametre', '0036_rename_typetableau_to_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pac',
            name='type_tableau',
            field=models.ForeignKey(blank=True, help_text='Version associée au PAC (Initial, Amendement, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacs', to='parametre.versions'),
        ),
    ]
