# Generated by Django 6.0 on 2026-04-16 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0026_merge_20260409_0851'),
        ('parametre', '0057_userprocessusrole_is_global'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pac',
            name='unique_pac_per_processus_annee_type_tableau',
        ),
        migrations.AddField(
            model_name='pac',
            name='num_amendement',
            field=models.PositiveIntegerField(default=0, help_text='0 = PAC Initial, 1 = Amendement 1, N = Amendement N'),
        ),
        migrations.AddConstraint(
            model_name='pac',
            constraint=models.UniqueConstraint(fields=('processus', 'annee', 'num_amendement'), name='unique_pac_per_processus_annee_num_amendement'),
        ),
        migrations.RemoveField(
            model_name='pac',
            name='type_tableau',
        ),
    ]
