# Generated by Django 6.0 on 2026-03-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0027_add_created_at_to_pac'),
    ]

    operations = [
        migrations.AddField(
            model_name='pac',
            name='raison_amendement',
            field=models.TextField(blank=True, help_text='Raison ou motif de la création de cet amendement', null=True),
        ),
    ]
