# Generated by Django 5.2.6 on 2025-09-30 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preuve',
            name='media',
        ),
        migrations.CreateModel(
            name='PreuveMedia',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage des médias")),
                ('description_media', models.TextField(blank=True, help_text='Description spécifique pour ce média', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.media')),
                ('preuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.preuve')),
            ],
            options={
                'verbose_name': 'Preuve Media',
                'verbose_name_plural': 'Preuves Medias',
                'db_table': 'preuve_media',
                'ordering': ['ordre', 'created_at'],
                'unique_together': {('preuve', 'media')},
            },
        ),
        migrations.AddField(
            model_name='preuve',
            name='medias',
            field=models.ManyToManyField(related_name='preuves', through='parametre.PreuveMedia', to='parametre.media'),
        ),
    ]
