# Generated by Django 5.2.6 on 2025-09-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0002_add_processus_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='medias/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='url_fichier',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
