# Generated by Django 5.2.6 on 2025-10-01 03:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0004_alter_media_fichier_activitylog_delete_preuvemedia_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('export', 'Export'), ('import', 'Import'), ('login', 'Connexion'), ('logout', 'Déconnexion')], max_length=20)),
                ('entity_type', models.CharField(choices=[('pac', 'PAC'), ('traitement', 'Traitement'), ('suivi', 'Suivi'), ('processus', 'Processus'), ('user', 'Utilisateur'), ('media', 'Média'), ('preuve', 'Preuve')], max_length=20)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='auth.user')),
            ],
            options={
                'verbose_name': "Log d'activité",
                'verbose_name_plural': "Logs d'activité",
                'db_table': 'activity_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_f9dfaa_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', '-created_at'], name='activity_lo_action_61fa17_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['entity_type', '-created_at'], name='activity_lo_entity__d6225b_idx'),
        ),
    ]
