# Generated by Django 5.2.6 on 2025-10-03 08:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0005_auto_20251001_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pac_echeance_notice_days', models.PositiveIntegerField(default=7)),
                ('traitement_delai_notice_days', models.PositiveIntegerField(default=7)),
                ('suivi_mise_en_oeuvre_notice_days', models.PositiveIntegerField(default=7)),
                ('suivi_cloture_notice_days', models.PositiveIntegerField(default=7)),
                ('reminders_count_before_day', models.PositiveIntegerField(default=3)),
                ('singleton_enforcer', models.BooleanField(default=True, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre de notification',
                'verbose_name_plural': 'Paramètres de notification',
                'db_table': 'notification_settings',
            },
        ),
    ]
