# Generated by Django 5.2.6 on 2025-10-03 08:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('parametre', '0006_notificationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOverride',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('pac_echeance_notice_days', models.PositiveIntegerField(blank=True, null=True)),
                ('traitement_delai_notice_days', models.PositiveIntegerField(blank=True, null=True)),
                ('suivi_mise_en_oeuvre_notice_days', models.PositiveIntegerField(blank=True, null=True)),
                ('suivi_cloture_notice_days', models.PositiveIntegerField(blank=True, null=True)),
                ('reminders_count_before_day', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametre.actiontype')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametre.direction')),
                ('processus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametre.processus')),
            ],
            options={
                'verbose_name': 'Override de notification',
                'verbose_name_plural': 'Overrides de notification',
                'db_table': 'notification_override',
                'constraints': [models.UniqueConstraint(condition=models.Q(('content_type__isnull', False), ('object_id__isnull', False)), fields=('content_type', 'object_id'), name='unique_object_override'), models.UniqueConstraint(condition=models.Q(('direction__isnull', False)), fields=('direction',), name='unique_direction_override'), models.UniqueConstraint(condition=models.Q(('processus__isnull', False)), fields=('processus',), name='unique_processus_override'), models.UniqueConstraint(condition=models.Q(('action_type__isnull', False)), fields=('action_type',), name='unique_action_type_override')],
            },
        ),
    ]
