# Generated by Django 5.2.6 on 2025-10-03 15:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0006_notificationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderEmailLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('context_hash', models.CharField(max_length=64)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log email de relance',
                'verbose_name_plural': 'Logs emails de relance',
                'db_table': 'reminder_email_log',
                'indexes': [models.Index(fields=['recipient', 'context_hash', 'sent_at'], name='reminder_em_recipie_c1b358_idx')],
            },
        ),
    ]
