# Generated by Django 5.2.6 on 2025-10-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0009_remove_notification_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='pac_echeance_notice_days',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='reminders_count_before_day',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='suivi_cloture_notice_days',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='suivi_mise_en_oeuvre_notice_days',
        ),
    ]
