# Generated by Django 5.2.6 on 2025-10-06 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0010_remove_unused_notification_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_host', models.CharField(default='smtp.gmail.com', help_text='Serveur SMTP (ex: smtp.gmail.com)', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587, help_text='Port SMTP (587 pour TLS, 465 pour SSL)')),
                ('email_host_user', models.EmailField(help_text="Adresse email pour l'authentification SMTP", max_length=254)),
                ('email_host_password', models.CharField(help_text="Mot de passe pour l'authentification SMTP", max_length=255)),
                ('email_use_tls', models.BooleanField(default=True, help_text='Utiliser TLS (recommandé)')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Utiliser SSL')),
                ('email_from_name', models.CharField(default='KORA', help_text="Nom affiché dans l'expéditeur", max_length=100)),
                ('email_timeout', models.PositiveIntegerField(default=30, help_text="Timeout en secondes pour l'envoi")),
                ('singleton_enforcer', models.BooleanField(default=True, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre email',
                'verbose_name_plural': 'Paramètres email',
                'db_table': 'email_settings',
            },
        ),
    ]
