# Generated by Django 5.2.6 on 2025-10-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0011_add_email_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='traitement_reminder_frequency_days',
            field=models.PositiveIntegerField(default=1, help_text='Fréquence des rappels après la notification initiale (en jours). 1 = chaque jour, 2 = tous les 2 jours, etc.'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='traitement_delai_notice_days',
            field=models.PositiveIntegerField(default=7, help_text='Nombre de jours avant le délai pour envoyer la première notification'),
        ),
    ]
