# Generated by Django 5.2.6 on 2025-10-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0012_add_reminder_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé'),
        ),
        migrations.AddField(
            model_name='appreciation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé'),
        ),
        migrations.AddField(
            model_name='direction',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé'),
        ),
        migrations.AddField(
            model_name='etatmiseenoeuvre',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé'),
        ),
        migrations.AddField(
            model_name='nature',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé'),
        ),
        migrations.AddField(
            model_name='processus',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé'),
        ),
        migrations.AddField(
            model_name='source',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé'),
        ),
        migrations.AddField(
            model_name='sousdirection',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé'),
        ),
    ]
