# Generated by Django 5.2.6 on 2025-10-09 02:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0013_add_is_active_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DysfonctionnementRecommandation',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dysfonctionnements_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dysfonctionnement/Recommandation',
                'verbose_name_plural': 'Dysfonctionnements/Recommandations',
                'db_table': 'dysfonctionnement_recommandation',
            },
        ),
    ]
