# Generated by Django 5.2.6 on 2025-10-14 02:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0014_dysfonctionnementrecommandation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequence',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(choices=[('Trimestrielle', 'Trimestrielle'), ('Semestrielle', 'Semestrielle'), ('Annuelle', 'Annuelle')], help_text='Nom de la fréquence', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fréquence',
                'verbose_name_plural': 'Fréquences',
                'db_table': 'frequence',
                'ordering': ['nom'],
            },
        ),
    ]
