# Generated by Django 5.2.6 on 2025-10-14 02:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0015_frequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodicite',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('a_realiser', models.DecimalField(decimal_places=2, help_text="Nombre d'actions à réaliser", max_digits=10)),
                ('realiser', models.DecimalField(decimal_places=2, default=0, help_text="Nombre d'actions réalisées", max_digits=10)),
                ('taux', models.DecimalField(decimal_places=2, default=0, help_text='Taux de réalisation en pourcentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequence_id', models.ForeignKey(help_text='Fréquence associée à cette périodicité', on_delete=django.db.models.deletion.CASCADE, related_name='periodicites', to='parametre.frequence')),
            ],
            options={
                'verbose_name': 'Périodicité',
                'verbose_name_plural': 'Périodicités',
                'db_table': 'periodicite',
                'ordering': ['frequence_id', 'created_at'],
            },
        ),
    ]
