# Generated by Django 5.2.6 on 2025-10-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0016_periodicite'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicite',
            name='periode',
            field=models.CharField(choices=[('T1', '1er Trimestre'), ('T2', '2ème Trimestre'), ('T3', '3ème Trimestre'), ('T4', '4ème Trimestre'), ('S1', '1er Semestre'), ('S2', '2ème Semestre'), ('A1', 'Année')], default='A1', help_text='Période spécifique de la fréquence', max_length=2),
        ),
    ]
