# Generated by Django 5.2.6 on 2025-10-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0017_periodicite_periode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequence',
            name='nom',
            field=models.CharField(help_text='Nom de la fréquence (ex: Trimestrielle, Semestrielle, Annuelle, Mensuelle, etc.)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='periodicite',
            name='periode',
            field=models.CharField(choices=[('T1', '1er Trimestre'), ('T2', '2ème Trimestre'), ('T3', '3ème Trimestre'), ('T4', '4ème Trimestre'), ('S1', '1er Semestre'), ('S2', '2ème Semestre'), ('A1', 'Année'), ('M1', 'Janvier'), ('M2', 'Février'), ('M3', 'Mars'), ('M4', 'Avril'), ('M5', 'Mai'), ('M6', 'Juin'), ('M7', 'Juillet'), ('M8', 'Août'), ('M9', 'Septembre'), ('M10', 'Octobre'), ('M11', 'Novembre'), ('M12', 'Décembre'), ('P1', 'Période 1'), ('P2', 'Période 2'), ('P3', 'Période 3'), ('P4', 'Période 4')], default='A1', help_text='Période spécifique de la fréquence', max_length=3),
        ),
    ]
