# Generated by Django 5.2.6 on 2025-10-14 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0018_alter_frequence_nom_alter_periodicite_periode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicite',
            name='periode',
            field=models.CharField(choices=[('T1', '1er Trimestre'), ('T2', '2ème Trimestre'), ('T3', '3ème Trimestre'), ('T4', '4ème Trimestre'), ('S1', '1er Semestre'), ('S2', '2ème Semestre'), ('A1', 'Année')], default='A1', help_text='Période spécifique de la fréquence', max_length=3),
        ),
        migrations.CreateModel(
            name='Cible',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Valeur de la cible (ex: 70)', max_digits=10)),
                ('condition', models.CharField(choices=[('≥', 'Supérieur ou égal à'), ('>', 'Supérieur à'), ('≤', 'Inférieur ou égal à'), ('<', 'Inférieur à'), ('=', 'Égal à'), ('≠', 'Différent de')], help_text='Condition de comparaison (ex: ≥)', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequence_id', models.ForeignKey(help_text='Périodicité associée à cette cible', on_delete=django.db.models.deletion.CASCADE, related_name='cibles', to='parametre.periodicite')),
            ],
            options={
                'verbose_name': 'Cible',
                'verbose_name_plural': 'Cibles',
                'db_table': 'cible',
                'ordering': ['frequence_id', 'created_at'],
            },
        ),
    ]
