# Generated by Django 5.2.6 on 2025-10-14 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0019_alter_periodicite_periode_cible'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDonnees',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Nom de la source (ex: Rapport annuel ANAC 2025)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('methode_id', models.ForeignKey(help_text='Méthode de cible associée à cette source', on_delete=django.db.models.deletion.CASCADE, related_name='sources_donnees', to='parametre.cible')),
            ],
            options={
                'verbose_name': 'Source des Données',
                'verbose_name_plural': 'Sources des Données',
                'db_table': 'source_donnees',
                'ordering': ['nom', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaSource',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Image', 'Image'), ('Vidéo', 'Vidéo'), ('Document', 'Document'), ('Lien', 'Lien')], help_text='Type de média', max_length=10)),
                ('url', models.URLField(help_text='URL du média', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.ForeignKey(help_text='Source associée à ce média', on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='parametre.sourcedonnees')),
            ],
            options={
                'verbose_name': 'Média Source',
                'verbose_name_plural': 'Médias Sources',
                'db_table': 'media_source',
                'ordering': ['source_id', 'type', 'created_at'],
            },
        ),
    ]
