# Generated by Django 5.2.6 on 2025-10-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0020_sourcedonnees_mediasource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediasource',
            options={'ordering': ['source_id', 'created_at'], 'verbose_name': 'Média Source', 'verbose_name_plural': 'Médias Sources'},
        ),
        migrations.RemoveField(
            model_name='mediasource',
            name='type',
        ),
        migrations.AlterField(
            model_name='mediasource',
            name='url',
            field=models.URLField(help_text='URL du média (Images, Vidéos, Documents, Liens)', max_length=500),
        ),
    ]
