# Generated by Django 5.2.6 on 2025-10-15 10:36

from django.db import migrations, models
import django.db.models.deletion


def migrate_cible_data(apps, schema_editor):
    """
    Migrer les données des cibles de Periodicite vers Frequence
    """
    Cible = apps.get_model('parametre', 'Cible')
    Periodicite = apps.get_model('parametre', 'Periodicite')
    Frequence = apps.get_model('parametre', 'Frequence')
    
    # Supprimer toutes les cibles existantes car elles référencent des périodicités
    # qui ne correspondent pas aux fréquences
    Cible.objects.all().delete()
    
    print("Cibles existantes supprimées pour éviter les conflits de migration")


def reverse_migrate_cible_data(apps, schema_editor):
    """
    Migration inverse - ne rien faire car on ne peut pas récupérer les données supprimées
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0021_alter_mediasource_options_remove_mediasource_type_and_more'),
    ]

    operations = [
        # D'abord, supprimer toutes les cibles existantes
        migrations.RunPython(migrate_cible_data, reverse_migrate_cible_data),
        
        # Ensuite, modifier le champ
        migrations.AlterField(
            model_name='cible',
            name='frequence_id',
            field=models.ForeignKey(
                help_text="Fréquence associée à cette cible",
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cibles',
                to='parametre.frequence'
            ),
        ),
    ]
