# Generated by Django 5.2.6 on 2025-10-15 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0022_auto_20251015_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cible',
            name='frequence_id',
            field=models.ForeignKey(blank=True, help_text='Fréquence associée à cette cible', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cibles', to='parametre.frequence'),
        ),
    ]
