# Generated by Django 5.0.7 on 2025-10-15 11:10

from django.db import migrations, models
import django.db.models.deletion


def migrate_cible_data(apps, schema_editor):
    """
    Migrer les données des cibles de frequence_id vers indicateur_id
    """
    Cible = apps.get_model('parametre', 'Cible')
    Indicateur = apps.get_model('dashboard', 'Indicateur')
    
    # Supprimer toutes les cibles existantes pour éviter les conflits
    # car nous changeons la structure de la relation
    Cible.objects.all().delete()
    print("Cibles existantes supprimées pour éviter les conflits de migration")


def reverse_migrate_cible_data(apps, schema_editor):
    """
    Migration inverse - ne rien faire car nous avons supprimé les données
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0023_alter_cible_frequence_id'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        # Supprimer l'ancien champ frequence_id
        migrations.RemoveField(
            model_name='cible',
            name='frequence_id',
        ),
        
        # Ajouter le nouveau champ indicateur_id (nullable temporairement)
        migrations.AddField(
            model_name='cible',
            name='indicateur_id',
            field=models.ForeignKey(
                help_text="Indicateur associé à cette cible",
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cibles',
                to='dashboard.indicateur',
                null=True,
                blank=True
            ),
        ),
        
        # Exécuter la migration des données
        migrations.RunPython(migrate_cible_data, reverse_migrate_cible_data),
    ]