# Generated by Django 5.2.6 on 2025-10-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0024_migrate_cible_to_indicateur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cible',
            options={'ordering': ['indicateur_id', 'created_at'], 'verbose_name': 'Cible', 'verbose_name_plural': 'Cibles'},
        ),
    ]
