# Generated by Django 5.2.6 on 2025-10-15 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_indicateur_frequence_id_delete_frequence'),
        ('parametre', '0025_alter_cible_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cible',
            name='indicateur_id',
            field=models.OneToOneField(help_text='Indicateur associé à cette cible', on_delete=django.db.models.deletion.CASCADE, related_name='cible', to='dashboard.indicateur'),
        ),
    ]
