# Generated by Django 5.2.6 on 2025-10-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0026_alter_cible_indicateur_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcedonnees',
            name='methode_id',
        ),
        migrations.DeleteModel(
            name='MediaSource',
        ),
        migrations.DeleteModel(
            name='SourceDonnees',
        ),
    ]
