# Generated by Django 5.2.6 on 2025-10-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0027_alter_periodicite_to_indicateur'),
        ('parametre', '0027_remove_sourcedonnees_mediasource'),
    ]

    operations = [
    ]
