# Generated by Django 5.2.6 on 2025-10-21 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0028_merge_20251016_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTableau',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Code du type (ex: INITIAL, AMENDEMENT_1, AMENDEMENT_2)', max_length=20, unique=True)),
                ('nom', models.CharField(help_text='Nom affiché du type (ex: Tableau Initial, Amendement 1)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description du type de tableau', null=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('couleur', models.CharField(default='#3B82F6', help_text="Couleur hexadécimale pour l'affichage", max_length=7)),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône à utiliser", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de Tableau',
                'verbose_name_plural': 'Types de Tableaux',
                'db_table': 'type_tableau',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
