# Generated by Django 5.2.6 on 2025-10-22 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0029_typetableau'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typetableau',
            options={'ordering': ['nom'], 'verbose_name': 'Type de Tableau', 'verbose_name_plural': 'Types de Tableaux'},
        ),
        migrations.RemoveField(
            model_name='typetableau',
            name='couleur',
        ),
        migrations.RemoveField(
            model_name='typetableau',
            name='icone',
        ),
        migrations.RemoveField(
            model_name='typetableau',
            name='ordre',
        ),
    ]
