# Generated by Django 5.2.6 on 2025-10-26 20:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0030_alter_typetableau_options_remove_typetableau_couleur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardNotificationSettings',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days_before_period_end', models.PositiveIntegerField(default=7, help_text='Nombre de jours avant la fin de la période pour envoyer la première notification')),
                ('days_after_period_end', models.PositiveIntegerField(default=7, help_text='Nombre de jours après la fin de la période pour envoyer une relance si non complété')),
                ('reminder_frequency_days', models.PositiveIntegerField(default=7, help_text='Fréquence des rappels après expiration (en jours). 1 = chaque jour, 7 = chaque semaine')),
                ('singleton_enforcer', models.BooleanField(default=True, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre de notification tableau de bord',
                'verbose_name_plural': 'Paramètres de notification tableaux de bord',
                'db_table': 'dashboard_notification_settings',
            },
        ),
    ]
