# Generated by Django 5.2.6 on 2025-10-28 13:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0031_dashboardnotificationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee', models.PositiveIntegerField(help_text='Année (ex: 2025)', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Année',
                'verbose_name_plural': 'Années',
                'db_table': 'annee',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='TypeTableauPac',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Code du type (ex: INITIAL, REVISION_01, REVISION_02)', max_length=20, unique=True)),
                ('nom', models.CharField(help_text='Nom affiché (ex: Révision initiale, Révision 01)', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de Tableau PAC',
                'verbose_name_plural': 'Types de Tableaux PAC',
                'db_table': 'type_tableau_pac',
                'ordering': ['code'],
            },
        ),
    ]
