# Generated by Django 5.2.6 on 2025-10-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0032_annee_typetableaupac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annee',
            name='description',
        ),
    ]
