# Generated by Django 5.2.6 on 2025-10-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pac', '0010_remove_pac_plan_conformite_and_more'),
        ('parametre', '0033_remove_annee_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeTableauPac',
        ),
        migrations.AddField(
            model_name='annee',
            name='description',
            field=models.TextField(blank=True, help_text="Description de l'année", null=True),
        ),
        migrations.AlterField(
            model_name='annee',
            name='annee',
            field=models.IntegerField(help_text='Année (ex: 2024, 2025)', unique=True),
        ),
        migrations.AlterField(
            model_name='annee',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Indique si l'année est active"),
        ),
    ]
