# Generated by Django 5.2.6 on 2025-10-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0034_delete_typetableaupac_annee_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annee',
            name='libelle',
            field=models.CharField(blank=True, help_text="Libellé optionnel (ex: 'Année fiscale 2024')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé'),
        ),
    ]
