# Generated by Django 5.2.6 on 2025-11-11 10:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0036_rename_typetableau_to_versions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticiteRisque',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(help_text='Libellé de la criticité (ex: Faible, Moyenne, Élevée, Très élevée)', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Criticité Risque',
                'verbose_name_plural': 'Criticités Risque',
                'db_table': 'criticite_risque',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='FrequenceRisque',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(help_text='Libellé de la fréquence (ex: Rare, Occasionnel, Fréquent, Très fréquent)', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fréquence Risque',
                'verbose_name_plural': 'Fréquences Risque',
                'db_table': 'frequence_risque',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='GraviteRisque',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(help_text='Libellé de la gravité (ex: Négligeable, Mineur, Modéré, Majeur, Critique)', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gravité Risque',
                'verbose_name_plural': 'Gravités Risque',
                'db_table': 'gravite_risque',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Risque',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(help_text='Libellé du type de risque', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description du type de risque', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Risque',
                'verbose_name_plural': 'Risques',
                'db_table': 'risque',
                'ordering': ['libelle'],
            },
        ),
        migrations.AlterField(
            model_name='versions',
            name='code',
            field=models.CharField(help_text='Code de la version (ex: INITIAL, AMENDEMENT_1, AMENDEMENT_2)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='versions',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la version', null=True),
        ),
        migrations.AlterField(
            model_name='versions',
            name='nom',
            field=models.CharField(help_text='Nom affiché de la version (ex: Tableau Initial, Amendement 1)', max_length=100),
        ),
    ]
