# Generated by Django 5.2.6 on 2025-11-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0037_criticiterisque_frequencerisque_graviterisque_risque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencerisque',
            name='valeur',
            field=models.CharField(blank=True, help_text='Valeur numérique de la fréquence pour le calcul de la criticité (ex: 1, 2, 3, 4, 5)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='graviterisque',
            name='code',
            field=models.CharField(blank=True, help_text='Code lettre de la gravité pour le calcul de la criticité (ex: A, B, C, D, E)', max_length=10, null=True),
        ),
    ]
