# Generated by Django 5.2.6 on 2025-11-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0038_frequencerisque_valeur_graviterisque_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='risque',
            name='niveaux_risque',
            field=models.JSONField(blank=True, default=list, help_text="Liste des niveaux de risque associés (ex: ['5A', '5B', '5C', '4A', '4B', '3A'])"),
        ),
    ]
