# Generated by Django 5.2.6 on 2025-11-18 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0039_risque_niveaux_risque'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutActionCDR',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Statut d'action CDR",
                'verbose_name_plural': "Statuts d'actions CDR",
                'db_table': 'statut_action_cdr',
                'ordering': ['nom'],
            },
        ),
    ]
