# Generated by Django 5.2.6 on 2025-11-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0040_statutactioncdr_actiontype_statuts_possibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, help_text='Description du média/fichier', null=True),
        ),
    ]
