# Generated by Django 5.2.6 on 2025-11-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0041_add_description_to_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='versions',
            name='raison',
            field=models.TextField(blank=True, help_text='Raison ou cause de la création de cette version (pour les amendements)', null=True),
        ),
    ]
