# Generated by Django 4.2.26 on 2025-11-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0044_remove_code_ordre_from_version_evaluation_cdr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versionevaluationcdr',
            options={'ordering': ['created_at', 'nom'], 'verbose_name': 'Version Évaluation CDR', 'verbose_name_plural': 'Versions Évaluation CDR'},
        ),
        migrations.RemoveField(
            model_name='versions',
            name='raison',
        ),
    ]
