# Generated by Django 4.2.26 on 2025-12-02 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0045_alter_versionevaluationcdr_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mois',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.IntegerField(help_text='Numéro du mois (1-12)', unique=True)),
                ('nom', models.CharField(help_text='Nom complet du mois (ex: Janvier, Février, etc.)', max_length=50, unique=True)),
                ('abreviation', models.CharField(help_text='Abréviation du mois (première lettre: J, F, M, etc.)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mois',
                'verbose_name_plural': 'Mois',
                'db_table': 'mois',
                'ordering': ['numero'],
            },
        ),
    ]
