# Generated by Django 4.2.26 on 2025-12-03 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
        ('parametre', '0047_populate_mois_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaDocument',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(help_text='Document associé à ce média', on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='documentation.document')),
                ('media', models.ForeignKey(help_text='Média associé à ce document', on_delete=django.db.models.deletion.CASCADE, related_name='document_medias', to='parametre.media')),
            ],
            options={
                'verbose_name': 'Média de Document',
                'verbose_name_plural': 'Médias de Documents',
                'db_table': 'media_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditionDocument',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Titre de l'édition", max_length=200)),
                ('description', models.TextField(blank=True, help_text="Description de l'édition", null=True)),
                ('numero_version', models.CharField(help_text='Numéro de version (ex: v1.0, v2.0)', max_length=20)),
                ('date_application', models.DateField(help_text="Date d'application de cette édition")),
                ('is_current', models.BooleanField(default=False, help_text='Indique si cette édition est actuellement active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(help_text='Document associé à cette édition', on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='documentation.document')),
            ],
            options={
                'verbose_name': 'Édition de Document',
                'verbose_name_plural': 'Éditions de Documents',
                'db_table': 'edition_document',
                'ordering': ['-created_at'],
                'unique_together': {('document', 'numero_version')},
            },
        ),
        migrations.CreateModel(
            name='AmendementDocument',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Titre de l'amendement", max_length=200)),
                ('description', models.TextField(blank=True, help_text="Description de l'amendement", null=True)),
                ('numero_version', models.CharField(help_text='Numéro de version (ex: v1.0, v2.0)', max_length=20)),
                ('date_application', models.DateField(help_text="Date d'application de cet amendement")),
                ('is_current', models.BooleanField(default=False, help_text='Indique si cet amendement est actuellement actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(help_text='Document associé à cet amendement', on_delete=django.db.models.deletion.CASCADE, related_name='amendements', to='documentation.document')),
                ('initial_ref', models.ForeignKey(blank=True, help_text="Référence à l'édition ou amendement initial (pour les amendements successifs)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amendements_suivants', to='parametre.amendementdocument')),
            ],
            options={
                'verbose_name': 'Amendement de Document',
                'verbose_name_plural': 'Amendements de Documents',
                'db_table': 'amendement_document',
                'ordering': ['-created_at'],
                'unique_together': {('document', 'numero_version')},
            },
        ),
    ]
