# Generated by Django 4.2.26 on 2025-12-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0048_mediadocument_editiondocument_amendementdocument'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amendementdocument',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='editiondocument',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='amendementdocument',
            name='date_application',
        ),
        migrations.RemoveField(
            model_name='amendementdocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='amendementdocument',
            name='initial_ref',
        ),
        migrations.RemoveField(
            model_name='amendementdocument',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='amendementdocument',
            name='numero_version',
        ),
        migrations.RemoveField(
            model_name='editiondocument',
            name='date_application',
        ),
        migrations.RemoveField(
            model_name='editiondocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='editiondocument',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='editiondocument',
            name='numero_version',
        ),
    ]
