# Generated by Django 4.2.26 on 2025-12-03 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0049_alter_amendementdocument_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDocument',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text="Nom de la catégorie (ex: 'Règlements', 'Procédures')", max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text="Code court pour la catégorie (ex: 'REG', 'PROC')", max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description de la catégorie', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de Document',
                'verbose_name_plural': 'Catégories de Documents',
                'db_table': 'categorie_document',
                'ordering': ['nom'],
            },
        ),
    ]
