# Generated by Django 4.2.26 on 2025-12-09 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0005_rename_categorie_to_type_document'),
        ('parametre', '0050_categoriedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text="Nom du type de document (ex: 'Règlements', 'Procédures')", max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text="Code court pour le type de document (ex: 'REG', 'PROC')", max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description du type de document', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de Document',
                'verbose_name_plural': 'Types de Documents',
                'db_table': 'type_document',
                'ordering': ['nom'],
            },
        ),
        migrations.DeleteModel(
            name='CategorieDocument',
        ),
    ]
