# Generated by Django 4.2.26 on 2025-12-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0051_rename_categorie_to_type_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='entity_type',
            field=models.CharField(choices=[('pac', 'PAC'), ('traitement', 'Traitement'), ('suivi', 'Suivi'), ('processus', 'Processus'), ('user', 'Utilisateur'), ('media', 'Média'), ('preuve', 'Preuve'), ('activite_periodique', 'Activité Périodique'), ('cdr', 'Cartographie de Risque'), ('document', 'Document'), ('document_edition', 'Édition de Document'), ('document_amendement', 'Amendement de Document'), ('tableau_bord', 'Tableau de Bord'), ('objectif', 'Objectif'), ('indicateur', 'Indicateur')], max_length=20),
        ),
    ]
