# Generated by Django 4.2.26 on 2025-12-15 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametre', '0052_alter_activitylog_entity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Code unique du rôle (ex: LECTURE, ECRITURE, EDITION, VALIDATION, SUPPRESSION)', max_length=50, unique=True)),
                ('nom', models.CharField(help_text='Nom du rôle (ex: Lecture, Écriture, Édition, Validation, Suppression)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description du rôle et de ses permissions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'db_table': 'role',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='UserProcessusRole',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_attribution', models.DateTimeField(auto_now_add=True, help_text="Date d'attribution du rôle")),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cette attribution de rôle est active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribue_par', models.ForeignKey(blank=True, help_text="Utilisateur qui a effectué l'attribution du rôle", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_attribues', to=settings.AUTH_USER_MODEL)),
                ('processus', models.ForeignKey(help_text='Processus concerné', on_delete=django.db.models.deletion.CASCADE, related_name='user_processus_roles', to='parametre.processus')),
                ('role', models.ForeignKey(help_text='Rôle attribué', on_delete=django.db.models.deletion.CASCADE, related_name='user_processus_roles', to='parametre.role')),
                ('user', models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='user_processus_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rôle Utilisateur Processus',
                'verbose_name_plural': 'Rôles Utilisateurs Processus',
                'db_table': 'user_processus_role',
                'ordering': ['-date_attribution'],
                'indexes': [models.Index(fields=['user', 'processus'], name='user_proces_user_id_2c814b_idx'), models.Index(fields=['user', 'processus', 'is_active'], name='user_proces_user_id_fcf067_idx')],
                'unique_together': {('user', 'processus', 'role')},
            },
        ),
        migrations.CreateModel(
            name='UserProcessus',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_attribution', models.DateTimeField(auto_now_add=True, help_text="Date d'attribution du processus à l'utilisateur")),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cette attribution est active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribue_par', models.ForeignKey(blank=True, help_text="Utilisateur qui a effectué l'attribution", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processus_attribues', to=settings.AUTH_USER_MODEL)),
                ('processus', models.ForeignKey(help_text="Processus attribué à l'utilisateur", on_delete=django.db.models.deletion.CASCADE, related_name='user_processus', to='parametre.processus')),
                ('user', models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='user_processus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attribution Processus Utilisateur',
                'verbose_name_plural': 'Attributions Processus Utilisateurs',
                'db_table': 'user_processus',
                'ordering': ['-date_attribution'],
                'unique_together': {('user', 'processus')},
            },
        ),
    ]
