# Generated by Django 4.2.26 on 2025-12-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0053_role_userprocessusrole_userprocessus'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprocessus',
            index=models.Index(fields=['user', 'processus'], name='user_proces_user_id_a896ed_idx'),
        ),
        migrations.AddIndex(
            model_name='userprocessus',
            index=models.Index(fields=['user', 'is_active'], name='user_proces_user_id_5768e3_idx'),
        ),
    ]
