# Generated by Django 4.2.26 on 2025-12-23 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametre', '0054_userprocessus_user_proces_user_id_a896ed_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('dashboard', 'Tableau de Bord'), ('pac', "PAC (Programme d'Amélioration Continue)"), ('cdr', 'Cartographie des Risques'), ('activite_periodique', 'Activité Périodique'), ('documentation', 'Documentation')], help_text="Nom de l'application", max_length=50, unique=True, verbose_name='Application')),
                ('is_enabled', models.BooleanField(default=True, help_text="Décocher pour mettre l'application en maintenance", verbose_name='Application activée')),
                ('maintenance_message', models.TextField(blank=True, help_text='Message affiché aux utilisateurs pendant la maintenance', null=True, verbose_name='Message de maintenance')),
                ('maintenance_start', models.DateTimeField(blank=True, help_text='Date et heure de début de la maintenance (optionnel)', null=True, verbose_name='Début de maintenance')),
                ('maintenance_end', models.DateTimeField(blank=True, help_text='Date et heure de fin prévue de la maintenance (optionnel)', null=True, verbose_name='Fin de maintenance prévue')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Dernier utilisateur ayant modifié cette configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Configuration Application',
                'verbose_name_plural': 'Configurations Applications',
                'db_table': 'application_config',
                'ordering': ['app_name'],
            },
        ),
    ]
