# Generated by Django 6.0 on 2026-04-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0055_applicationconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preuve',
            old_name='description',
            new_name='titre',
        ),
    ]
