# Generated by Django 6.0 on 2026-01-07 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite_periodique', '0008_add_livrable_and_date_realisation_to_suivisap'),
        ('parametre', '0055_applicationconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLivrable',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre_document', models.CharField(help_text='Titre du document/livrable', max_length=255)),
                ('autre_livrable', models.TextField(blank=True, help_text='Description ou autres informations sur le livrable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medias', models.ManyToManyField(blank=True, help_text='Médias associés à ce livrable', related_name='media_livrables', to='parametre.media')),
                ('suivi_ap', models.ForeignKey(help_text='Suivi AP associé à ce livrable', on_delete=django.db.models.deletion.CASCADE, related_name='media_livrables', to='activite_periodique.suivisap')),
            ],
            options={
                'verbose_name': 'Média Livrable',
                'verbose_name_plural': 'Médias Livrables',
                'db_table': 'media_livrable',
                'ordering': ['-created_at'],
            },
        ),
    ]
