# Generated by Django 6.0 on 2026-01-12 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0056_create_media_livrable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='email_host_password_encrypted',
            field=models.TextField(blank=True, default='', help_text="Mot de passe chiffré pour l'authentification SMTP"),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='enable_rate_limiting',
            field=models.BooleanField(default=True, help_text="Activer la limitation du taux d'envoi"),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_settings_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='last_test_success',
            field=models.DateTimeField(blank=True, help_text='Date du dernier test réussi', null=True),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='max_emails_per_hour',
            field=models.PositiveIntegerField(default=100, help_text="Nombre maximum d'emails par heure"),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='max_recipients_per_email',
            field=models.PositiveIntegerField(default=50, help_text='Nombre maximum de destinataires par email'),
        ),
        migrations.AddField(
            model_name='reminderemaillog',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text="Message d'erreur si échec"),
        ),
        migrations.AddField(
            model_name='reminderemaillog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text="IP de l'émetteur", null=True),
        ),
        migrations.AddField(
            model_name='reminderemaillog',
            name='success',
            field=models.BooleanField(default=True, help_text="Si l'envoi a réussi"),
        ),
        migrations.AddField(
            model_name='reminderemaillog',
            name='user',
            field=models.ForeignKey(blank=True, help_text="Utilisateur qui a déclenché l'envoi", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_host_password',
            field=models.CharField(blank=True, default='', help_text='[DÉPRÉCIÉ] Utilisez email_host_password_encrypted', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_timeout',
            field=models.PositiveIntegerField(default=10, help_text="Timeout en secondes pour l'envoi (max 15 recommandé)"),
        ),
        migrations.AddIndex(
            model_name='reminderemaillog',
            index=models.Index(fields=['success', 'sent_at'], name='reminder_em_success_9797b2_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderemaillog',
            index=models.Index(fields=['user', 'sent_at'], name='reminder_em_user_id_399a2e_idx'),
        ),
    ]
