# Generated by Django 6.0 on 2026-01-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0057_add_email_security_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='email_host_password',
            field=models.CharField(blank=True, default='', help_text='Mot de passe SMTP (sera chiffré automatiquement)', max_length=255),
        ),
    ]
