# Generated by Django 6.0 on 2026-04-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activite_periodique', '0010_remove_activiteperiodique_unique_activite_periodique_per_processus_annee_type_tableau_user_and_more'),
        ('cartographie_risque', '0015_alter_cdr_unique_together_cdr_num_amendement_and_more'),
        ('dashboard', '0019_alter_tableaubord_options_and_more'),
        ('pac', '0027_remove_pac_unique_pac_per_processus_annee_type_tableau_and_more'),
        ('parametre', '0057_userprocessusrole_is_global'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Versions',
        ),
        migrations.RenameIndex(
            model_name='userprocessusrole',
            new_name='user_proces_user_id_cf19e6_idx',
            old_name='user_prcs_role_global_idx',
        ),
    ]
