# Generated by Django 6.0 on 2026-02-02 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0058_update_password_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicite',
            name='preuve',
            field=models.ForeignKey(blank=True, help_text='Preuve justifiant la réalisation ou non de cette périodicité', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodicites', to='parametre.preuve'),
        ),
    ]
