# Generated by Django 5.2.6 on 2026-04-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0058_delete_versions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='device_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='os_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
