# Generated by Django 5.2.6 on 2026-04-27 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0059_add_device_info_to_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_attempted', models.CharField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=20, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(choices=[('user_not_found', 'Utilisateur introuvable'), ('wrong_password', 'Mot de passe incorrect'), ('inactive_account', 'Compte désactivé')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failed_login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentative de connexion échouée',
                'verbose_name_plural': 'Tentatives de connexion échouées',
                'db_table': 'failed_login_attempt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='failed_logi_created_01c293_idx'), models.Index(fields=['ip_address', '-created_at'], name='failed_logi_ip_addr_3e83bf_idx'), models.Index(fields=['email_attempted', '-created_at'], name='failed_logi_email_a_4efb0b_idx')],
            },
        ),
    ]
