# Generated by Django 6.0 on 2026-02-02 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0059_add_preuve_to_periodicite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_civilite', models.CharField(blank=True, choices=[('M.', 'M.'), ('Mme', 'Mme'), ('Mlle', 'Mlle')], help_text='Titre de civilité (M., Mme, Mlle)', max_length=10, null=True, verbose_name='Titre de civilité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
                'verbose_name_plural': 'Profils Utilisateurs',
                'db_table': 'user_profile',
                'ordering': ['user__username'],
            },
        ),
    ]
