# Generated by Django 5.2.6 on 2026-02-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0060_add_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
