# Generated by Django 5.2.6 on 2026-04-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0060_add_failedloginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSecurityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Désactiver pour suspendre toute protection sans supprimer la config.', verbose_name='Blocage actif')),
                ('ip_max_attempts', models.PositiveIntegerField(default=10, help_text="Nombre d'échecs depuis la même IP avant blocage.", verbose_name='Seuil IP (tentatives)')),
                ('email_max_attempts', models.PositiveIntegerField(default=5, help_text="Nombre d'échecs sur le même email avant blocage du compte.", verbose_name='Seuil email (tentatives)')),
                ('window_minutes', models.PositiveIntegerField(default=15, help_text='Durée de la fenêtre de comptage des échecs.', verbose_name='Fenêtre glissante (min)')),
                ('ip_block_duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Durée blocage IP (min)')),
                ('email_block_duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Durée blocage email (min)')),
                ('whitelist_ips', models.TextField(blank=True, default='', help_text='Une IP par ligne. Ces IPs ne seront jamais bloquées (ex: serveurs internes).', verbose_name='IPs en liste blanche')),
            ],
            options={
                'verbose_name': 'Configuration sécurité login',
                'verbose_name_plural': 'Configuration sécurité login',
                'db_table': 'login_security_config',
            },
        ),
        migrations.CreateModel(
            name='LoginBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('ip', 'Adresse IP'), ('email', 'Email')], max_length=10)),
                ('value', models.CharField(db_index=True, max_length=254)),
                ('blocked_until', models.DateTimeField()),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('is_manual', models.BooleanField(default=False, help_text="Coché si ajouté manuellement via l'admin.", verbose_name='Blocage manuel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blocage login',
                'verbose_name_plural': 'Blocages login',
                'db_table': 'login_block',
                'ordering': ['-created_at'],
                'unique_together': {('block_type', 'value')},
            },
        ),
    ]
