# Generated by Django 6.0 on 2026-02-25 13:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('parametre', '0061_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_app', models.CharField(help_text="App d'origine : pac, dashboard, activite_periodique, etc.", max_length=64)),
                ('notification_type', models.CharField(help_text='Type métier : traitement, suivi, objective, etc.', max_length=64)),
                ('object_id', models.UUIDField(blank=True, help_text="PK de l'objet lié", null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('action_url', models.CharField(blank=True, max_length=512, null=True)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute')], default='medium', max_length=16)),
                ('due_date', models.DateField(blank=True, help_text="Date d'échéance si applicable", null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='Date/heure de lecture', null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, help_text='Date/heure de masquage', null=True)),
                ('sent_by_email_at', models.DateTimeField(blank=True, help_text="Date/heure d'envoi par email (si inclus dans un rappel)", null=True)),
                ('shown_in_ui_at', models.DateTimeField(blank=True, help_text="Date/heure de première affichage dans l'interface", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type du modèle lié (ex: TraitementPac)', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='Destinataire de la notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at', 'created_at'], name='notificatio_user_id_5212da_idx'), models.Index(fields=['user', 'source_app'], name='notificatio_user_id_46f5bb_idx'), models.Index(fields=['content_type', 'object_id'], name='notificatio_content_0c2d97_idx'), models.Index(fields=['user', 'dismissed_at'], name='notificatio_user_id_94107f_idx')],
            },
        ),
    ]
