# Generated by Django 6.0 on 2026-04-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0061_add_login_security_config_and_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThrottleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Désactiver supprime toute limitation de débit.', verbose_name='Throttling actif')),
                ('anon_rate', models.CharField(default='100/min', help_text='Requêtes/période pour les IPs non authentifiées. Ex : 100/min', max_length=20, verbose_name='Taux anonymes')),
                ('user_rate', models.CharField(default='600/min', help_text='Requêtes/période pour les utilisateurs connectés. Ex : 600/min', max_length=20, verbose_name='Taux utilisateurs')),
                ('sensitive_rate', models.CharField(default='10/min', help_text='Login, reset password, invitation. Ex : 10/min', max_length=20, verbose_name='Taux endpoints sensibles')),
            ],
            options={
                'verbose_name': 'Configuration throttling',
                'verbose_name_plural': 'Configuration throttling',
                'db_table': 'throttle_config',
            },
        ),
    ]
