# Generated by Django 5.2.6 on 2026-05-29 09:26

import parametre.media_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0062_add_throttle_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=parametre.media_paths.media_upload_path),
        ),
        migrations.AlterField(
            model_name='throttleconfig',
            name='anon_rate',
            field=models.CharField(default='100/minute', help_text='Requêtes/période pour les IPs non authentifiées. Ex : 100/minute', max_length=20, verbose_name='Taux anonymes'),
        ),
        migrations.AlterField(
            model_name='throttleconfig',
            name='sensitive_rate',
            field=models.CharField(default='10/minute', help_text='Login, reset password, invitation. Ex : 10/minute', max_length=20, verbose_name='Taux endpoints sensibles'),
        ),
        migrations.AlterField(
            model_name='throttleconfig',
            name='user_rate',
            field=models.CharField(default='600/minute', help_text='Requêtes/période pour les utilisateurs connectés. Ex : 600/minute', max_length=20, verbose_name='Taux utilisateurs'),
        ),
    ]
