# Generated by Django 6.0 on 2026-02-26 10:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0062_add_notification_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPolicy',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('pac', "Plans d'action de conformité (PAC)"), ('dashboard', 'Tableaux de bord'), ('activite_periodique', 'Activités périodiques')], help_text='Domaine concerné par cette politique (ex: pac, dashboard, activite_periodique).', max_length=64, unique=True)),
                ('days_before', models.PositiveIntegerField(default=7, help_text="Nombre de jours avant l'échéance pour commencer à envoyer des notifications.")),
                ('days_after', models.PositiveIntegerField(default=0, help_text="Nombre de jours après l'échéance avant la première relance.")),
                ('reminder_frequency_days', models.PositiveIntegerField(default=1, help_text='Fréquence des relances après échéance (en jours). 1 = chaque jour, 7 = chaque semaine.')),
                ('description', models.TextField(blank=True, default='', help_text="Description fonctionnelle de cette politique (visible dans l'admin).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Politique de notification',
                'verbose_name_plural': 'Politiques de notification',
                'db_table': 'notification_policy',
                'ordering': ['scope'],
            },
        ),
    ]
