# Generated by Django 6.0 on 2026-06-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0063_alter_media_fichier_alter_throttleconfig_anon_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecaptchaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Désactiver ignore complètement la vérification reCAPTCHA.', verbose_name='reCAPTCHA activé')),
                ('site_key', models.CharField(blank=True, default='', help_text='Laissez vide pour utiliser RECAPTCHA_SITE_KEY du fichier .env.', max_length=255, verbose_name='Clé publique (site key)')),
                ('secret_key', models.CharField(blank=True, default='', help_text='Laissez vide pour utiliser RECAPTCHA_SECRET_KEY du fichier .env.', max_length=255, verbose_name='Clé secrète (secret key)')),
                ('min_score', models.FloatField(default=0.5, help_text='Entre 0.0 (bot) et 1.0 (humain). Recommandé : 0.5.', verbose_name='Score minimum v3')),
                ('apply_to_login', models.BooleanField(default=True, verbose_name='Actif sur la connexion')),
                ('apply_to_register', models.BooleanField(default=True, verbose_name="Actif sur l'inscription")),
                ('apply_to_invitation', models.BooleanField(default=True, verbose_name="Actif sur la complétion d'invitation")),
                ('apply_to_password_reset', models.BooleanField(default=True, verbose_name='Actif sur la réinitialisation de mot de passe')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration reCAPTCHA',
                'verbose_name_plural': 'Configuration reCAPTCHA',
                'db_table': 'recaptcha_config',
            },
        ),
    ]
