# Generated by Django 6.0 on 2026-06-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0064_add_recaptcha_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recaptchaconfig',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='recaptchaconfig',
            name='secret_key_encrypted',
            field=models.TextField(blank=True, default='', editable=False, help_text='Chiffré automatiquement. Ne pas modifier directement.', verbose_name='Clé secrète chiffrée'),
        ),
    ]
