# Generated by Django 5.2.6 on 2026-06-08 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0068_recaptcha_per_endpoint_min_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Si activé, un code par email est requis après chaque connexion.', verbose_name='2FA activé')),
                ('otp_lifetime_seconds', models.PositiveIntegerField(default=300, help_text='Exemples : 60 = 1 min, 300 = 5 min, 3600 = 1h, 86400 = 1 jour, 31536000 = 1 an.', verbose_name='Durée de validité du code (secondes)')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Nombre de codes incorrects avant invalidation du code.', verbose_name='Tentatives max')),
                ('code_length', models.PositiveIntegerField(default=6, help_text='Nombre de chiffres du code OTP (4 à 8 recommandé).', verbose_name='Longueur du code')),
            ],
            options={
                'verbose_name': 'Configuration 2FA',
                'verbose_name_plural': 'Configuration 2FA',
                'db_table': 'two_factor_config',
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Identifiant temporaire transmis au frontend pour désigner cette session 2FA.', unique=True, verbose_name='Clé de session')),
                ('code_hash', models.CharField(help_text='Code haché — jamais stocké en clair.', max_length=256, verbose_name='Hash du code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Tentatives')),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Code OTP email',
                'verbose_name_plural': 'Codes OTP email',
                'db_table': 'email_otp',
                'ordering': ['-created_at'],
            },
        ),
    ]
