# Generated by Django 6.0 on 2026-06-16 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0072_unique_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginsecurityconfig',
            name='ip_block_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='loginsecurityconfig',
            name='ip_max_attempts',
        ),
        migrations.RemoveField(
            model_name='loginsecurityconfig',
            name='whitelist_ips',
        ),
        migrations.AlterField(
            model_name='twofactorconfig',
            name='code_length',
            field=models.PositiveIntegerField(default=6, help_text='Nombre de chiffres du code OTP (4 à 8).', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(8)], verbose_name='Longueur du code'),
        ),
        migrations.AlterField(
            model_name='twofactorconfig',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3, help_text='Nombre de codes incorrects avant invalidation du code (1 à 10).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Tentatives max'),
        ),
        migrations.AlterField(
            model_name='twofactorconfig',
            name='otp_lifetime_seconds',
            field=models.PositiveIntegerField(default=86400, help_text="Durée pendant laquelle l'utilisateur n'est pas redemandé après une vérification réussie. Minimum 300 s (5 min), maximum 31 536 000 s (1 an). Exemples : 3600 = 1h, 86400 = 1 jour, 604800 = 7 jours, 2592000 = 30 jours.", validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(31536000)], verbose_name='Durée de la session 2FA (secondes)'),
        ),
    ]
