# Generated by Django 5.2.6 on 2026-06-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0073_remove_ip_blocking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='receive_reminders',
            field=models.BooleanField(default=False, help_text='Si True, les utilisateurs ayant ce rôle reçoivent les emails de rappel individuels (PAC, CDR, etc.). Laisser False pour les rôles système (admin, superviseur).'),
        ),
    ]
