# Generated by Django 4.2.26 on 2025-12-17 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametre', '0054_userprocessus_user_proces_user_id_a896ed_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(db_index=True, help_text="Nom de l'application (ex: 'cdr', 'dashboard', 'pac')", max_length=50)),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_validate', models.BooleanField(default=False)),
                ('can_create_amendement', models.BooleanField(default=False)),
                ('can_manage_details', models.BooleanField(default=False)),
                ('can_manage_evaluations', models.BooleanField(default=False)),
                ('can_manage_plans_action', models.BooleanField(default=False)),
                ('can_manage_suivis', models.BooleanField(default=False)),
                ('can_edit_when_validated', models.BooleanField(default=False, help_text="Peut modifier même si l'entité est validée")),
                ('can_edit_only_own', models.BooleanField(default=False, help_text='Peut modifier seulement ses propres créations')),
                ('can_delete_only_own', models.BooleanField(default=False, help_text='Peut supprimer seulement ses propres créations')),
                ('can_validate_own', models.BooleanField(default=False, help_text='Peut valider ses propres créations')),
                ('date_debut', models.DateTimeField(blank=True, help_text='Début de validité de la permission', null=True)),
                ('date_fin', models.DateTimeField(blank=True, help_text='Fin de validité de la permission', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indique si cette permission est active')),
                ('source_type', models.CharField(default='role_mapping', help_text="Source: 'role_mapping' ou 'custom_override'", max_length=50)),
                ('source_id', models.UUIDField(blank=True, help_text='Référence à USERPROCESSUSROLE ou PERMISSION_OVERRIDE', null=True)),
                ('last_calculated_at', models.DateTimeField(auto_now=True, help_text='Quand cette permission a été calculée (pour nettoyage cache)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission Application',
                'verbose_name_plural': 'Permissions Applications',
                'db_table': 'app_permission',
                'ordering': ['user', 'app_name', 'processus', 'permission_action'],
            },
        ),
        migrations.CreateModel(
            name='PermissionAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(help_text="Nom de l'application (ex: 'cdr', 'dashboard', 'pac')", max_length=50)),
                ('code', models.CharField(help_text="Code unique de l'action (ex: 'create_cdr', 'update_tableau')", max_length=50)),
                ('nom', models.CharField(help_text="Nom de l'action (ex: 'Créer CDR', 'Modifier Tableau')", max_length=100)),
                ('description', models.TextField(blank=True, help_text="Description de l'action", null=True)),
                ('category', models.CharField(blank=True, help_text="Catégorie (ex: 'main', 'details', 'evaluation', 'plan_action')", max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cette action est active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Action de Permission',
                'verbose_name_plural': 'Actions de Permissions',
                'db_table': 'permission_action',
                'ordering': ['app_name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RolePermissionMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('granted', models.BooleanField(default=True, help_text='Ce rôle accorde-t-il cette permission ?')),
                ('conditions', models.JSONField(blank=True, help_text='Conditions contextuelles (ex: can_edit_when_validated, can_edit_only_own)', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Priorité si plusieurs mappings pour le même rôle')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si ce mapping est actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_action', models.ForeignKey(help_text='Action de permission concernée', on_delete=django.db.models.deletion.CASCADE, related_name='role_mappings', to='permissions.permissionaction')),
                ('role', models.ForeignKey(help_text='Rôle concerné', on_delete=django.db.models.deletion.CASCADE, related_name='permission_mappings', to='parametre.role')),
            ],
            options={
                'verbose_name': 'Mapping Rôle-Permission',
                'verbose_name_plural': 'Mappings Rôle-Permission',
                'db_table': 'role_permission_mapping',
                'ordering': ['role', 'priority', 'permission_action'],
            },
        ),
        migrations.CreateModel(
            name='PermissionOverride',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(help_text="Nom de l'application (ex: 'cdr', 'dashboard', 'pac')", max_length=50)),
                ('granted', models.BooleanField(help_text='Permission accordée (true) ou refusée (false)')),
                ('conditions', models.JSONField(blank=True, help_text='Conditions spécifiques pour cet override', null=True)),
                ('raison', models.TextField(help_text='Pourquoi cette permission personnalisée (audit)')),
                ('date_debut', models.DateTimeField(blank=True, help_text='Début de validité', null=True)),
                ('date_fin', models.DateTimeField(blank=True, help_text='Fin de validité', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indique si cet override est actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(help_text='Qui a créé cette permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides_crees', to=settings.AUTH_USER_MODEL)),
                ('permission_action', models.ForeignKey(help_text='Action de permission concernée', on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='permissions.permissionaction')),
                ('processus', models.ForeignKey(help_text='Processus concerné', on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='parametre.processus')),
                ('user', models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Personnalisée',
                'verbose_name_plural': 'Permissions Personnalisées',
                'db_table': 'permission_override',
                'ordering': ['user', 'app_name', 'processus', 'permission_action'],
            },
        ),
        migrations.CreateModel(
            name='PermissionAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(help_text="Nom de l'application (ex: 'cdr', 'dashboard', 'pac')", max_length=50)),
                ('action', models.CharField(help_text="Code de l'action demandée (ex: 'create_cdr', 'update_tableau')", max_length=50)),
                ('entity_id', models.UUIDField(blank=True, help_text="UUID de l'entité concernée (CDR, Tableau, PAC, etc.)", null=True)),
                ('entity_type', models.CharField(blank=True, help_text="Type d'entité (ex: 'cdr', 'tableau', 'pac')", max_length=50, null=True)),
                ('granted', models.BooleanField(db_index=True, help_text='Permission accordée (true) ou refusée (false)')),
                ('reason', models.TextField(blank=True, help_text='Raison du refus si applicable', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP de la requête', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent du navigateur', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Quand la vérification a eu lieu')),
                ('resolution_method', models.CharField(default='db', help_text="Méthode de résolution: 'cache', 'db', 'override', 'super_admin'", max_length=50)),
                ('execution_time_ms', models.FloatField(blank=True, help_text="Temps d'exécution en millisecondes", null=True)),
                ('cache_hit', models.BooleanField(default=False, help_text='Cache utilisé ou non')),
                ('processus', models.ForeignKey(help_text='Processus concerné', on_delete=django.db.models.deletion.CASCADE, related_name='permission_audits', to='parametre.processus')),
                ('user', models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='permission_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit de Permission',
                'verbose_name_plural': 'Audits de Permissions',
                'db_table': 'permission_audit',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='permissionaction',
            index=models.Index(fields=['app_name', 'code', 'is_active'], name='permission__app_nam_b2881a_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionaction',
            index=models.Index(fields=['app_name', 'category'], name='permission__app_nam_5bf9d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permissionaction',
            unique_together={('app_name', 'code')},
        ),
        migrations.AddField(
            model_name='apppermission',
            name='permission_action',
            field=models.ForeignKey(help_text='Action de permission concernée', on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to='permissions.permissionaction'),
        ),
        migrations.AddField(
            model_name='apppermission',
            name='processus',
            field=models.ForeignKey(help_text='Processus concerné', on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to='parametre.processus'),
        ),
        migrations.AddField(
            model_name='apppermission',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rolepermissionmapping',
            index=models.Index(fields=['role', 'granted', 'is_active'], name='role_permis_role_id_74448e_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermissionmapping',
            index=models.Index(fields=['permission_action', 'granted'], name='role_permis_permiss_764c3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermissionmapping',
            unique_together={('role', 'permission_action')},
        ),
        migrations.AddIndex(
            model_name='permissionoverride',
            index=models.Index(fields=['user', 'processus', 'app_name', 'is_active'], name='permission__user_id_f3a61a_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionoverride',
            index=models.Index(fields=['cree_par', 'created_at'], name='permission__cree_pa_827671_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permissionoverride',
            unique_together={('user', 'processus', 'app_name', 'permission_action')},
        ),
        migrations.AddIndex(
            model_name='permissionaudit',
            index=models.Index(fields=['user', 'app_name', 'timestamp'], name='permission__user_id_494bba_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionaudit',
            index=models.Index(fields=['app_name', 'action', 'granted'], name='permission__app_nam_6d50e7_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionaudit',
            index=models.Index(fields=['entity_type', 'entity_id', 'timestamp'], name='permission__entity__5a1180_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionaudit',
            index=models.Index(fields=['timestamp'], name='permission__timesta_25abff_idx'),
        ),
        migrations.AddIndex(
            model_name='apppermission',
            index=models.Index(fields=['user', 'processus', 'app_name', 'is_active'], name='app_permiss_user_id_bd25c7_idx'),
        ),
        migrations.AddIndex(
            model_name='apppermission',
            index=models.Index(fields=['user', 'app_name', 'is_active'], name='app_permiss_user_id_3ff905_idx'),
        ),
        migrations.AddIndex(
            model_name='apppermission',
            index=models.Index(fields=['app_name', 'is_active'], name='app_permiss_app_nam_bb3cff_idx'),
        ),
        migrations.AddIndex(
            model_name='apppermission',
            index=models.Index(fields=['last_calculated_at'], name='app_permiss_last_ca_094992_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apppermission',
            unique_together={('user', 'processus', 'app_name', 'permission_action')},
        ),
    ]
