"""
Django settings for KORA project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Charger les variables d'environnement depuis un fichier .env (si présent)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==================== ENVIRONNEMENT ====================
# DJANGO_ENV peut être: "development", "staging", "production", etc.
DJANGO_ENV = os.getenv('DJANGO_ENV', 'development').lower()

# ==================== SECRET KEY ====================
# SECURITY WARNING: keep the secret key used in production secret!
# Priorité à DJANGO_SECRET_KEY, puis SECRET_KEY (compat .env existant). Pas de clé en dur.
SECRET_KEY = (
    os.getenv('SECRET_KEY')
)

# ==================== DEBUG ====================
# En production, on force DEBUG à False
if DJANGO_ENV == 'production':
    DEBUG = False
else:
    # Par défaut, DEBUG reste True en développement si non spécifié
    DEBUG = os.getenv('DJANGO_DEBUG', 'true').lower() == 'true'

# ==================== ALLOWED HOSTS ====================
# En prod, configure DJANGO_ALLOWED_HOSTS="kora.mondomaine.com,api.mondomaine.com"
_allowed_hosts_env = os.getenv('DJANGO_ALLOWED_HOSTS')
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_apscheduler',  # Pour la planification des tâches (notifications)
    'pac',
    'activite_periodique',
    'documentation',
    'parametre',
    'dashboard',
    'cartographie_risque',
    'permissions',
    'analyse_tableau',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'shared.cors_middleware.CORSContentTypeMiddleware',  # Corriger le Content-Type des requêtes CORS
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'shared.middleware.MediaFrameOptionsMiddleware',  # Notre middleware personnalisé (avant XFrameOptionsMiddleware)
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'shared.middleware.JWTCookieMiddleware',  # Doit être AVANT ApplicationMaintenanceMiddleware
    'middleware.application_maintenance.ApplicationMaintenanceMiddleware',  # Vérification mode maintenance (après JWT)
]

ROOT_URLCONF = 'KORA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'KORA.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Par défaut: SQLite en développement.
# En production: configurez les variables d'environnement pour utiliser Postgres (ou autre SGBD).

DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite').lower()

if DB_ENGINE == 'postgres':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'kora'),
            'USER': os.getenv('DB_USER', 'kora'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    # Fallback SQLite (développement)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files (uploads)
MEDIA_URL = '/medias/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'medias')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite dev server
    "http://127.0.0.1:5173",
    "http://localhost:5174",  # Vite dev server (port alternatif)
    "http://127.0.0.1:5174",
    "https://sapiential-tommy-unelaborate.ngrok-free.dev",  # ngrok tunnel
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False  # Sécurité
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Configuration des cookies
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
# En production (DJANGO_ENV=production), forcer les cookies sécurisés
SESSION_COOKIE_SECURE = not DEBUG

# Configuration CSRF
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = not DEBUG

# Configuration X-Frame-Options pour permettre l'affichage en iframe des fichiers média
# Le middleware MediaFrameOptionsMiddleware gère spécifiquement les fichiers /medias/
X_FRAME_OPTIONS = 'DENY'  # Protection par défaut, le middleware personnalisé override pour /medias/

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'shared.authentication.CookieJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'shared.parsers.PlainTextAsJSONParser',  # Parser pour les requêtes CORS de Safari avec text/plain
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'EXCEPTION_HANDLER': 'shared.exception_handler.custom_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=8),  # Durée d'une journée de travail
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# Configuration reCAPTCHA
RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY', None)  
RECAPTCHA_SITE_KEY = os.getenv('RECAPTCHA_SITE_KEY', None)    
RECAPTCHA_MIN_SCORE = float(os.getenv('RECAPTCHA_MIN_SCORE', '0.5'))

# Désactiver reCAPTCHA temporairement pour le développement
if not RECAPTCHA_SECRET_KEY or not RECAPTCHA_SITE_KEY:
    RECAPTCHA_SECRET_KEY = None
    RECAPTCHA_SITE_KEY = None

# ==================== EMAIL / SMTP ====================
# Configure via environment variables
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@kora.local')

# ==================== PASSWORD RESET / INVITATION TOKENS ====================
# Délai d'expiration pour les tokens de réinitialisation de mot de passe et d'invitation
# Par défaut Django utilise 3 jours (259200 secondes) pour les resets.
# Ici on force 4 heures pour la réinitialisation de mot de passe (14400 secondes),
# sauf si la variable d'environnement PASSWORD_RESET_TIMEOUT est définie.
PASSWORD_RESET_TIMEOUT = int(os.getenv('PASSWORD_RESET_TIMEOUT', '14400'))  # 4 heures en secondes (4 * 60 * 60)
INVITATION_TOKEN_TIMEOUT = int(os.getenv('INVITATION_TOKEN_TIMEOUT', '604800'))  # 7 jours en secondes (surchargé via .env si besoin)
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'false').lower() == 'true'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'KORA Notifications <noreply@kora.local>')

# Frontend base URL for building links in emails
FRONTEND_BASE_URL = os.getenv('FRONTEND_BASE_URL', 'http://localhost:5173')

# ==================== EMAIL ENCRYPTION ====================
# Clé de chiffrement pour les mots de passe SMTP (Security by Design)
EMAIL_ENCRYPTION_KEY = os.getenv('EMAIL_ENCRYPTION_KEY', None)

if not EMAIL_ENCRYPTION_KEY:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning("⚠️ EMAIL_ENCRYPTION_KEY non définie ! Ajoutez-la dans votre fichier .env")
    logger.warning("⚠️ Consultez ENCRYPTION_KEY.txt pour obtenir votre clé")

# Configuration de logging pour le debug
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'shared.authentication': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'pac.views': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'parametre.scheduler': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apscheduler': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
