# Generated by Django 5.2.6 on 2025-10-14 02:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(help_text="Numéro de l'objectif (ex: OB01)", max_length=20, unique=True)),
                ('libelle', models.CharField(help_text="Libellé de l'objectif (ex: Assurer à 70% la mise en œuvre du plan annuel)", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(help_text="Utilisateur qui a créé l'objectif", on_delete=django.db.models.deletion.CASCADE, related_name='objectives_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objectif',
                'verbose_name_plural': 'Objectifs',
                'db_table': 'objectives',
                'ordering': ['number'],
            },
        ),
    ]
