# Generated by Django 5.2.6 on 2026-04-02 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(help_text="Libellé de l'indicateur (ex: Taux de mise en œuvre des actions du plan ANAC 2025)", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Indicateur',
                'verbose_name_plural': 'Indicateurs',
                'db_table': 'indicateur',
                'ordering': ['objective_id', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, help_text="Numéro de l'objectif (ex: OB01)", max_length=20)),
                ('libelle', models.CharField(help_text="Libellé de l'objectif (ex: Assurer à 70% la mise en œuvre du plan annuel)", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Objectif',
                'verbose_name_plural': 'Objectifs',
                'db_table': 'objectives',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.TextField(help_text="Libellé de l'observation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
                'db_table': 'observation',
                'ordering': ['indicateur_id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableauBord',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee', models.PositiveIntegerField(help_text='Année du tableau de bord (ex: 2025)')),
                ('raison_amendement', models.TextField(blank=True, help_text="Raison de création de l'amendement", null=True)),
                ('is_validated', models.BooleanField(default=False, help_text='Indique si le tableau de bord est validé pour la saisie des trimestres')),
                ('date_validation', models.DateTimeField(blank=True, help_text='Date de validation du tableau', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tableau de bord',
                'verbose_name_plural': 'Tableaux de bord',
                'db_table': 'tableau_bord',
                'ordering': ['-annee', 'processus__numero_processus', 'type_tableau__code'],
            },
        ),
    ]
