# Generated by Django 5.2.6 on 2026-04-02 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('parametre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateur',
            name='frequence_id',
            field=models.ForeignKey(blank=True, help_text='Fréquence de mesure de cet indicateur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='parametre.frequence'),
        ),
        migrations.AddField(
            model_name='objectives',
            name='cree_par',
            field=models.ForeignKey(help_text="Utilisateur qui a créé l'objectif", on_delete=django.db.models.deletion.CASCADE, related_name='objectives_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='objective_id',
            field=models.ForeignKey(help_text='Objectif associé à cet indicateur', on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='dashboard.objectives'),
        ),
        migrations.AddField(
            model_name='observation',
            name='cree_par',
            field=models.ForeignKey(help_text="Utilisateur qui a créé l'observation", on_delete=django.db.models.deletion.CASCADE, related_name='observations_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observation',
            name='indicateur_id',
            field=models.OneToOneField(help_text='Indicateur associé à cette observation', on_delete=django.db.models.deletion.CASCADE, related_name='observation', to='dashboard.indicateur'),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableaux_bord_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='initial_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amendements', to='dashboard.tableaubord'),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='processus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableaux_bord', to='parametre.processus'),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='type_tableau',
            field=models.ForeignKey(help_text='Type de tableau de bord', on_delete=django.db.models.deletion.CASCADE, related_name='tableaux_bord', to='parametre.versions'),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='valide_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a validé le tableau', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tableaux_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objectives',
            name='tableau_bord',
            field=models.ForeignKey(blank=True, help_text='Tableau de bord auquel appartient cet objectif', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='dashboard.tableaubord'),
        ),
        migrations.AddConstraint(
            model_name='tableaubord',
            constraint=models.UniqueConstraint(fields=('annee', 'processus', 'type_tableau'), name='uniq_tableau_per_annee_processus_type'),
        ),
        migrations.AddConstraint(
            model_name='objectives',
            constraint=models.UniqueConstraint(condition=models.Q(('tableau_bord__isnull', False)), fields=('tableau_bord', 'number'), name='uniq_objective_number_per_tableau'),
        ),
    ]
