# Generated by Django 5.2.6 on 2025-10-14 02:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequence',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Nom de la fréquence (ex: Mensuel, Trimestriel, Annuel)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description de la fréquence', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fréquence',
                'verbose_name_plural': 'Fréquences',
                'db_table': 'frequence',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(help_text="Libellé de l'indicateur (ex: Taux de mise en œuvre des actions du plan ANAC 2025)", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequence_id', models.ForeignKey(help_text='Fréquence de mesure de cet indicateur', on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='dashboard.frequence')),
                ('objective_id', models.ForeignKey(help_text='Objectif associé à cet indicateur', on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='dashboard.objectives')),
            ],
            options={
                'verbose_name': 'Indicateur',
                'verbose_name_plural': 'Indicateurs',
                'db_table': 'indicateur',
                'ordering': ['objective_id', 'libelle'],
            },
        ),
    ]
