# Generated by Django 5.2.6 on 2025-10-14 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_frequence_indicateur'),
        ('parametre', '0015_frequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicateur',
            name='frequence_id',
            field=models.ForeignKey(help_text='Fréquence de mesure de cet indicateur', on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='parametre.frequence'),
        ),
        migrations.DeleteModel(
            name='Frequence',
        ),
    ]
