# Generated by Django 5.2.6 on 2025-10-17 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_indicateur_frequence_id_delete_frequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.TextField(help_text="Libellé de l'observation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(help_text="Utilisateur qui a créé l'observation", on_delete=django.db.models.deletion.CASCADE, related_name='observations_creees', to=settings.AUTH_USER_MODEL)),
                ('indicateur_id', models.OneToOneField(help_text='Indicateur associé à cette observation', on_delete=django.db.models.deletion.CASCADE, related_name='observation', to='dashboard.indicateur')),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
                'db_table': 'observation',
                'ordering': ['indicateur_id', 'created_at'],
            },
        ),
    ]
