# Generated by Django 5.2.6 on 2025-10-20 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_observation'),
        ('parametre', '0028_merge_20251016_1210'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableauBord',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee', models.PositiveIntegerField(help_text='Année du tableau de bord (ex: 2025)')),
                ('type_tableau', models.CharField(choices=[('INITIAL', 'Tableau de bord Initial'), ('AMENDEMENT_1', 'Amendement 1'), ('AMENDEMENT_2', 'Amendement 2')], default='INITIAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableaux_bord_crees', to=settings.AUTH_USER_MODEL)),
                ('initial_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amendements', to='dashboard.tableaubord')),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableaux_bord', to='parametre.processus')),
            ],
            options={
                'verbose_name': 'Tableau de bord',
                'verbose_name_plural': 'Tableaux de bord',
                'db_table': 'tableau_bord',
                'ordering': ['-annee', 'processus__numero_processus', 'type_tableau'],
            },
        ),
        migrations.AddField(
            model_name='objectives',
            name='tableau_bord',
            field=models.ForeignKey(blank=True, help_text='Tableau de bord auquel appartient cet objectif', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='dashboard.tableaubord'),
        ),
        migrations.AddConstraint(
            model_name='tableaubord',
            constraint=models.UniqueConstraint(condition=models.Q(('type_tableau', 'INITIAL')), fields=('annee', 'processus'), name='uniq_initial_par_annee_processus'),
        ),
        migrations.AddConstraint(
            model_name='tableaubord',
            constraint=models.UniqueConstraint(condition=models.Q(('type_tableau', 'AMENDEMENT_1')), fields=('annee', 'processus'), name='uniq_amendement1_par_annee_processus'),
        ),
        migrations.AddConstraint(
            model_name='tableaubord',
            constraint=models.UniqueConstraint(condition=models.Q(('type_tableau', 'AMENDEMENT_2')), fields=('annee', 'processus'), name='uniq_amendement2_par_annee_processus'),
        ),
    ]
