# Generated by Django 5.2.6 on 2025-10-20 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_tableaubord_objectives_tableau_bord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='objectives',
            constraint=models.UniqueConstraint(fields=('tableau_bord', 'number'), name='uniq_objective_number_per_tableau'),
        ),
    ]
