# Generated by Django 5.2.6 on 2025-10-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_objectives_uniq_objective_number_per_tableau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableaubord',
            name='type_tableau',
            field=models.CharField(choices=[('INITIAL', 'Amendement 0'), ('AMENDEMENT_1', 'Amendement 1'), ('AMENDEMENT_2', 'Amendement 2')], default='INITIAL', max_length=20),
        ),
    ]
