# Generated by Django 5.2.6 on 2025-10-21 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_tableaubord_type_tableau'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='objectives',
            name='uniq_objective_number_per_tableau',
        ),
        migrations.AddConstraint(
            model_name='objectives',
            constraint=models.UniqueConstraint(condition=models.Q(('tableau_bord__isnull', False)), fields=('tableau_bord', 'number'), name='uniq_objective_number_per_tableau'),
        ),
    ]
