# Generated by Django 5.2.6 on 2025-10-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_objectives_uniq_objective_number_per_tableau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectives',
            name='number',
            field=models.CharField(help_text="Numéro de l'objectif (ex: OB01)", max_length=20),
        ),
    ]
