# Generated by Django 5.2.6 on 2025-10-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_objectives_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableaubord',
            name='type_tableau',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('AMENDEMENT_1', 'Amendement 1'), ('AMENDEMENT_2', 'Amendement 2')], default='INITIAL', max_length=20),
        ),
    ]
