# Generated by Django 5.2.6 on 2025-10-21 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_tableaubord_type_tableau'),
        ('parametre', '0028_merge_20251016_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicateur',
            name='frequence_id',
            field=models.ForeignKey(blank=True, help_text='Fréquence de mesure de cet indicateur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='parametre.frequence'),
        ),
    ]
