# Generated by Django 5.2.6 on 2025-10-21 15:30

from django.db import migrations, models
import django.db.models.deletion


def migrate_type_tableau_to_fk(apps, schema_editor):
    """
    Migre les données de type_tableau du CharField vers le ForeignKey
    """
    TableauBord = apps.get_model('dashboard', 'TableauBord')
    TypeTableau = apps.get_model('parametre', 'TypeTableau')
    
    # Mapping des anciennes valeurs vers les TypeTableau
    type_mapping = {}
    for tt in TypeTableau.objects.all():
        type_mapping[tt.code] = tt
    
    # Remplir le nouveau champ avec la première valeur TypeTableau disponible par défaut
    default_type = TypeTableau.objects.filter(code='INITIAL').first()
    if not default_type:
        # Fallback si INITIAL n'existe pas
        default_type = TypeTableau.objects.first()
    
    if default_type:
        # Mettre à jour les tableaux de bord
        for tableau in TableauBord.objects.all():
            if tableau.type_tableau_old and tableau.type_tableau_old in type_mapping:
                tableau.type_tableau_new = type_mapping[tableau.type_tableau_old]
            else:
                tableau.type_tableau_new = default_type
            tableau.save(update_fields=['type_tableau_new'])


def reverse_migrate_type_tableau(apps, schema_editor):
    """Pas de conversion inverse"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_make_frequence_id_optional'),
        ('parametre', '0029_typetableau'),
    ]

    operations = [
        # Étape 0: Modifier les options du modèle AVANT de changer les champs
        migrations.AlterModelOptions(
            name='tableaubord',
            options={'ordering': ['-annee', 'processus__numero_processus'], 'verbose_name': 'Tableau de bord', 'verbose_name_plural': 'Tableaux de bord'},
        ),
        # Étape 0.5: Supprimer les anciennes contraintes AVANT de renommer les champs
        migrations.RemoveConstraint(
            model_name='tableaubord',
            name='uniq_initial_par_annee_processus',
        ),
        migrations.RemoveConstraint(
            model_name='tableaubord',
            name='uniq_amendement1_par_annee_processus',
        ),
        migrations.RemoveConstraint(
            model_name='tableaubord',
            name='uniq_amendement2_par_annee_processus',
        ),
        # Étape 1: Ajouter la nouvelle colonne type_tableau (ForeignKey)
        migrations.AddField(
            model_name='tableaubord',
            name='type_tableau_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tableaux_bord_new', to='parametre.typetableau'),
        ),
        # Étape 2: Renommer l'ancienne colonne
        migrations.RenameField(
            model_name='tableaubord',
            old_name='type_tableau',
            new_name='type_tableau_old',
        ),
        # Étape 3: Migrer les données
        migrations.RunPython(
            migrate_type_tableau_to_fk,
            reverse_migrate_type_tableau,
        ),
        # Étape 4: Renommer la nouvelle colonne vers l'ancien nom
        migrations.RenameField(
            model_name='tableaubord',
            old_name='type_tableau_new',
            new_name='type_tableau',
        ),
        # Étape 5: Supprimer l'ancienne colonne
        migrations.RemoveField(
            model_name='tableaubord',
            name='type_tableau_old',
        ),
        # Étape 5.5: Rendre le champ NOT NULL après la migration des données
        migrations.AlterField(
            model_name='tableaubord',
            name='type_tableau',
            field=models.ForeignKey(help_text='Type de tableau de bord', on_delete=django.db.models.deletion.CASCADE, related_name='tableaux_bord', to='parametre.typetableau'),
        ),
        # Étape 6: Restaurer les options du modèle avec le bon ordering
        migrations.AlterModelOptions(
            name='tableaubord',
            options={'ordering': ['-annee', 'processus__numero_processus', 'type_tableau__ordre'], 'verbose_name': 'Tableau de bord', 'verbose_name_plural': 'Tableaux de bord'},
        ),
        # Étape 8: Ajouter la nouvelle contrainte
        migrations.AddConstraint(
            model_name='tableaubord',
            constraint=models.UniqueConstraint(fields=('annee', 'processus', 'type_tableau'), name='uniq_tableau_per_annee_processus_type'),
        ),
    ]
