# Generated by Django 5.2.6 on 2025-10-22 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_convert_type_tableau_to_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableaubord',
            options={'ordering': ['-annee', 'processus__numero_processus', 'type_tableau__code'], 'verbose_name': 'Tableau de bord', 'verbose_name_plural': 'Tableaux de bord'},
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='date_validation',
            field=models.DateTimeField(blank=True, help_text='Date de validation du tableau', null=True),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='etat_validation',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('VALIDATED', 'Validé')], default='DRAFT', help_text='État de validation du tableau de bord', max_length=20),
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='valide_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a validé le tableau', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tableaux_valides', to=settings.AUTH_USER_MODEL),
        ),
    ]
