# Generated by Django 5.2.6 on 2025-10-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_add_validation_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableaubord',
            name='etat_validation',
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='Indique si le tableau de bord est validé pour la saisie des trimestres'),
        ),
    ]
