# Generated by Django 5.2.6 on 2025-10-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_replace_etat_with_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectives',
            name='number',
            field=models.CharField(blank=True, help_text="Numéro de l'objectif (ex: OB01)", max_length=20),
        ),
    ]
