# Generated by Django 5.2.6 on 2025-10-31 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_objectives_number'),
        ('parametre', '0036_rename_typetableau_to_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableaubord',
            name='type_tableau',
            field=models.ForeignKey(help_text='Type de tableau de bord', on_delete=django.db.models.deletion.CASCADE, related_name='tableaux_bord', to='parametre.versions'),
        ),
    ]
