# Generated by Django 5.2.6 on 2025-12-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_rename_typetableau_to_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableaubord',
            name='raison_amendement',
            field=models.TextField(blank=True, help_text="Raison de création de l'amendement", null=True),
        ),
    ]


