# Generated by Django 6.0 on 2026-04-16 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_merge_20260409_0851'),
        ('parametre', '0057_userprocessusrole_is_global'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableaubord',
            options={'ordering': ['-annee', 'processus__numero_processus', 'num_amendement'], 'verbose_name': 'Tableau de bord', 'verbose_name_plural': 'Tableaux de bord'},
        ),
        migrations.RemoveConstraint(
            model_name='tableaubord',
            name='uniq_tableau_per_annee_processus_type',
        ),
        migrations.AddField(
            model_name='tableaubord',
            name='num_amendement',
            field=models.PositiveIntegerField(default=0, help_text='0 = Tableau Initial, 1 = Amendement 1, N = Amendement N'),
        ),
        migrations.AddConstraint(
            model_name='tableaubord',
            constraint=models.UniqueConstraint(fields=('annee', 'processus', 'num_amendement'), name='uniq_tableau_per_annee_processus_num_amendement'),
        ),
        migrations.RemoveField(
            model_name='tableaubord',
            name='type_tableau',
        ),
    ]
