# Generated by Django 5.2.6 on 2025-11-11 10:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametre', '0037_criticiterisque_frequencerisque_graviterisque_risque_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CDR',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee', models.PositiveIntegerField(help_text='Année de la cartographie des risques (ex: 2025)')),
                ('is_validated', models.BooleanField(default=False, help_text='Indique si la cartographie est validée')),
                ('date_validation', models.DateTimeField(blank=True, help_text='Date de validation de la cartographie', null=True)),
                ('cree_par', models.ForeignKey(help_text='Utilisateur qui a créé la cartographie', on_delete=django.db.models.deletion.CASCADE, related_name='cdrs_crees', to=settings.AUTH_USER_MODEL)),
                ('processus', models.ForeignKey(help_text='Processus associé à la cartographie', on_delete=django.db.models.deletion.CASCADE, related_name='cdrs', to='parametre.processus')),
                ('type_tableau', models.ForeignKey(help_text='Type de tableau (Initial, Amendement, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='cdrs', to='parametre.versions')),
                ('valide_par', models.ForeignKey(blank=True, help_text='Utilisateur qui a validé la cartographie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdrs_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartographie des Risques',
                'verbose_name_plural': 'Cartographies des Risques',
                'db_table': 'cdr',
                'ordering': ['-annee', 'processus'],
                'unique_together': {('annee', 'processus', 'type_tableau')},
            },
        ),
        migrations.CreateModel(
            name='DetailsCDR',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_cdr', models.CharField(help_text="Numéro d'identification du détail CDR", max_length=50)),
                ('activites', models.TextField(help_text='Activités concernées')),
                ('objectifs', models.TextField(help_text='Objectifs visés')),
                ('evenements_indesirables_risques', models.TextField(help_text='Événements indésirables et risques identifiés')),
                ('causes', models.TextField(help_text='Causes des risques')),
                ('consequences', models.TextField(help_text='Conséquences potentielles')),
                ('cdr', models.ForeignKey(help_text='Cartographie des risques associée', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='cartographie_risque.cdr')),
            ],
            options={
                'verbose_name': 'Détail CDR',
                'verbose_name_plural': 'Détails CDR',
                'db_table': 'details_cdr',
                'ordering': ['numero_cdr', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationRisque',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criticite', models.ForeignKey(help_text='Criticité du risque', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='parametre.criticiterisque')),
                ('details_cdr', models.ForeignKey(help_text='Détail CDR associé', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='cartographie_risque.detailscdr')),
                ('frequence', models.ForeignKey(help_text='Fréquence du risque', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='parametre.frequencerisque')),
                ('gravite', models.ForeignKey(help_text='Gravité du risque', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='parametre.graviterisque')),
                ('risque', models.ForeignKey(help_text='Type de risque', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='parametre.risque')),
            ],
            options={
                'verbose_name': 'Évaluation des Risques',
                'verbose_name_plural': 'Évaluations des Risques',
                'db_table': 'evaluation_risque',
                'ordering': ['details_cdr', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanAction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actions_mesures', models.TextField(help_text='Actions et mesures à mettre en œuvre')),
                ('delai_realisation', models.DateField(blank=True, help_text='Délai de réalisation prévu', null=True)),
                ('details_cdr', models.ForeignKey(help_text='Détail CDR associé', on_delete=django.db.models.deletion.CASCADE, related_name='plans_action', to='cartographie_risque.detailscdr')),
                ('responsable', models.ForeignKey(blank=True, help_text='Responsable de la mise en œuvre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_action_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Plan d'Action",
                'verbose_name_plural': "Plans d'Action",
                'db_table': 'plan_action',
                'ordering': ['details_cdr', 'delai_realisation', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuiviAction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_realisation', models.DateField(blank=True, help_text='Date de réalisation effective', null=True)),
                ('statut_action', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('suspendu', 'Suspendu'), ('annule', 'Annulé')], default='en_cours', help_text="Statut de l'action", max_length=20)),
                ('date_cloture', models.DateField(blank=True, help_text="Date de clôture de l'action", null=True)),
                ('critere_efficacite_objectif_vise', models.TextField(blank=True, help_text="Critère d'efficacité et objectif visé", null=True)),
                ('resultats_mise_en_oeuvre', models.TextField(blank=True, help_text='Résultats de la mise en œuvre des actions', null=True)),
                ('element_preuve', models.ForeignKey(blank=True, help_text='Élément de preuve (média)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis_actions', to='parametre.media')),
                ('plan_action', models.ForeignKey(help_text="Plan d'action associé", on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='cartographie_risque.planaction')),
            ],
            options={
                'verbose_name': "Suivi d'Action",
                'verbose_name_plural': "Suivis d'Actions",
                'db_table': 'suivi_action',
                'ordering': ['plan_action', '-date_realisation', 'created_at'],
            },
        ),
    ]
