# Generated by Django 5.2.6 on 2026-04-02 09:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsCDR',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_cdr', models.CharField(blank=True, help_text="Numéro d'identification du détail CDR", max_length=50, null=True)),
                ('activites', models.TextField(blank=True, help_text='Activités concernées', null=True)),
                ('objectifs', models.TextField(blank=True, help_text='Objectifs visés', null=True)),
                ('evenements_indesirables_risques', models.TextField(blank=True, help_text='Événements indésirables et risques identifiés', null=True)),
                ('causes', models.TextField(blank=True, help_text='Causes des risques', null=True)),
                ('consequences', models.TextField(blank=True, help_text='Conséquences potentielles', null=True)),
            ],
            options={
                'verbose_name': 'Détail CDR',
                'verbose_name_plural': 'Détails CDR',
                'db_table': 'details_cdr',
                'ordering': ['numero_cdr', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationRisque',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Évaluation des Risques',
                'verbose_name_plural': 'Évaluations des Risques',
                'db_table': 'evaluation_risque',
                'ordering': ['details_cdr', 'version_evaluation__created_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanAction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actions_mesures', models.TextField(help_text='Actions et mesures à mettre en œuvre')),
                ('delai_realisation', models.DateField(blank=True, help_text='Délai de réalisation prévu', null=True)),
            ],
            options={
                'verbose_name': "Plan d'Action",
                'verbose_name_plural': "Plans d'Action",
                'db_table': 'plan_action',
                'ordering': ['details_cdr', 'delai_realisation', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanActionResponsable',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(help_text='UUID du responsable')),
            ],
            options={
                'verbose_name': "Responsable Plan d'Action",
                'verbose_name_plural': "Responsables Plans d'Action",
                'db_table': 'plan_action_responsable',
                'ordering': ['plan_action', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuiviAction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_realisation', models.DateField(blank=True, help_text='Date de réalisation effective', null=True)),
                ('date_cloture', models.DateField(blank=True, help_text="Date de clôture de l'action", null=True)),
                ('critere_efficacite_objectif_vise', models.TextField(blank=True, help_text="Critère d'efficacité et objectif visé", null=True)),
                ('resultats_mise_en_oeuvre', models.TextField(blank=True, help_text='Résultats de la mise en œuvre des actions', null=True)),
            ],
            options={
                'verbose_name': "Suivi d'Action",
                'verbose_name_plural': "Suivis d'Actions",
                'db_table': 'suivi_action',
                'ordering': ['plan_action', '-date_realisation', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CDR',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee', models.PositiveIntegerField(help_text='Année de la cartographie des risques (ex: 2025)')),
                ('is_validated', models.BooleanField(default=False, help_text='Indique si la cartographie est validée')),
                ('raison_amendement', models.TextField(blank=True, help_text='Raison ou cause de la création de cet amendement', null=True)),
                ('date_validation', models.DateTimeField(blank=True, help_text='Date de validation de la cartographie', null=True)),
                ('cree_par', models.ForeignKey(help_text='Utilisateur qui a créé la cartographie', on_delete=django.db.models.deletion.CASCADE, related_name='cdrs_crees', to=settings.AUTH_USER_MODEL)),
                ('initial_ref', models.ForeignKey(blank=True, help_text='Référence au CDR initial (pour les amendements)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amendements', to='cartographie_risque.cdr')),
            ],
            options={
                'verbose_name': 'Cartographie des Risques',
                'verbose_name_plural': 'Cartographies des Risques',
                'db_table': 'cdr',
                'ordering': ['-annee', 'processus'],
            },
        ),
    ]
