# Generated by Django 5.2.6 on 2025-11-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie_risque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailscdr',
            name='activites',
            field=models.TextField(blank=True, help_text='Activités concernées', null=True),
        ),
        migrations.AlterField(
            model_name='detailscdr',
            name='causes',
            field=models.TextField(blank=True, help_text='Causes des risques', null=True),
        ),
        migrations.AlterField(
            model_name='detailscdr',
            name='consequences',
            field=models.TextField(blank=True, help_text='Conséquences potentielles', null=True),
        ),
        migrations.AlterField(
            model_name='detailscdr',
            name='evenements_indesirables_risques',
            field=models.TextField(blank=True, help_text='Événements indésirables et risques identifiés', null=True),
        ),
        migrations.AlterField(
            model_name='detailscdr',
            name='numero_cdr',
            field=models.CharField(blank=True, help_text="Numéro d'identification du détail CDR", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detailscdr',
            name='objectifs',
            field=models.TextField(blank=True, help_text='Objectifs visés', null=True),
        ),
    ]
