# Generated by Django 5.2.6 on 2026-04-02 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartographie_risque', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('parametre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cdr',
            name='processus',
            field=models.ForeignKey(help_text='Processus associé à la cartographie', on_delete=django.db.models.deletion.CASCADE, related_name='cdrs', to='parametre.processus'),
        ),
        migrations.AddField(
            model_name='cdr',
            name='type_tableau',
            field=models.ForeignKey(help_text='Type de tableau (Initial, Amendement, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='cdrs', to='parametre.versions'),
        ),
        migrations.AddField(
            model_name='cdr',
            name='valide_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a validé la cartographie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdrs_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detailscdr',
            name='cdr',
            field=models.ForeignKey(help_text='Cartographie des risques associée', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='cartographie_risque.cdr'),
        ),
        migrations.AddField(
            model_name='evaluationrisque',
            name='criticite',
            field=models.ForeignKey(blank=True, help_text='Criticité du risque', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='parametre.criticiterisque'),
        ),
        migrations.AddField(
            model_name='evaluationrisque',
            name='details_cdr',
            field=models.ForeignKey(help_text='Détail CDR associé', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='cartographie_risque.detailscdr'),
        ),
        migrations.AddField(
            model_name='evaluationrisque',
            name='frequence',
            field=models.ForeignKey(blank=True, help_text='Fréquence du risque', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='parametre.frequencerisque'),
        ),
        migrations.AddField(
            model_name='evaluationrisque',
            name='gravite',
            field=models.ForeignKey(blank=True, help_text='Gravité du risque', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='parametre.graviterisque'),
        ),
        migrations.AddField(
            model_name='evaluationrisque',
            name='risque',
            field=models.ForeignKey(blank=True, help_text='Type de risque', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='parametre.risque'),
        ),
        migrations.AddField(
            model_name='evaluationrisque',
            name='version_evaluation',
            field=models.ForeignKey(help_text="Version de l'évaluation (Initiale, Réévaluation 1, etc.)", on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='parametre.versionevaluationcdr'),
        ),
        migrations.AddField(
            model_name='planaction',
            name='details_cdr',
            field=models.ForeignKey(help_text='Détail CDR associé', on_delete=django.db.models.deletion.CASCADE, related_name='plans_action', to='cartographie_risque.detailscdr'),
        ),
        migrations.AddField(
            model_name='planaction',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Responsable principal (Direction) - DEPRECATED: Utiliser PlanActionResponsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_action_responsable', to='parametre.direction'),
        ),
        migrations.AddField(
            model_name='planactionresponsable',
            name='content_type',
            field=models.ForeignKey(help_text='Type de responsable (Direction, SousDirection ou Service)', limit_choices_to={'model__in': ('direction', 'sousdirection', 'service')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='planactionresponsable',
            name='plan_action',
            field=models.ForeignKey(help_text="Plan d'action associé", on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='cartographie_risque.planaction'),
        ),
        migrations.AddField(
            model_name='suiviaction',
            name='element_preuve',
            field=models.ForeignKey(blank=True, help_text='Élément de preuve (peut contenir plusieurs médias)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis_actions', to='parametre.preuve'),
        ),
        migrations.AddField(
            model_name='suiviaction',
            name='plan_action',
            field=models.ForeignKey(help_text="Plan d'action associé", on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='cartographie_risque.planaction'),
        ),
        migrations.AddField(
            model_name='suiviaction',
            name='statut_action',
            field=models.ForeignKey(blank=True, help_text="Statut de l'action", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suivis_actions', to='parametre.statutactioncdr'),
        ),
        migrations.AlterUniqueTogether(
            name='cdr',
            unique_together={('annee', 'processus', 'type_tableau')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluationrisque',
            unique_together={('details_cdr', 'version_evaluation')},
        ),
        migrations.AlterUniqueTogether(
            name='planactionresponsable',
            unique_together={('plan_action', 'content_type', 'object_id')},
        ),
    ]
