# Generated by Django 5.2.6 on 2025-11-12 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie_risque', '0002_alter_detailscdr_activites_alter_detailscdr_causes_and_more'),
        ('parametre', '0037_criticiterisque_frequencerisque_graviterisque_risque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationrisque',
            name='criticite',
            field=models.ForeignKey(blank=True, help_text='Criticité du risque', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='parametre.criticiterisque'),
        ),
        migrations.AlterField(
            model_name='evaluationrisque',
            name='frequence',
            field=models.ForeignKey(blank=True, help_text='Fréquence du risque', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='parametre.frequencerisque'),
        ),
        migrations.AlterField(
            model_name='evaluationrisque',
            name='gravite',
            field=models.ForeignKey(blank=True, help_text='Gravité du risque', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='parametre.graviterisque'),
        ),
        migrations.AlterField(
            model_name='evaluationrisque',
            name='risque',
            field=models.ForeignKey(blank=True, help_text='Type de risque', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='parametre.risque'),
        ),
    ]
