# Generated by Django 5.2.6 on 2025-11-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie_risque', '0004_change_responsable_to_direction'),
        ('parametre', '0038_frequencerisque_valeur_graviterisque_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suiviaction',
            name='element_preuve',
            field=models.ForeignKey(blank=True, help_text='Élément de preuve (peut contenir plusieurs médias)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis_actions', to='parametre.preuve'),
        ),
    ]
