# Generated by Django 5.2.6 on 2025-11-16 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie_risque', '0005_alter_suiviaction_element_preuve'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdr',
            name='initial_ref',
            field=models.ForeignKey(blank=True, help_text='Référence au CDR initial (pour les amendements)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amendements', to='cartographie_risque.cdr'),
        ),
    ]
