# Generated by Django 5.2.6 on 2025-11-18 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie_risque', '0006_cdr_initial_ref'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('parametre', '0039_risque_niveaux_risque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planaction',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Responsable principal (Direction) - DEPRECATED: Utiliser PlanActionResponsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_action_responsable', to='parametre.direction'),
        ),
        migrations.CreateModel(
            name='PlanActionResponsable',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(help_text='UUID du responsable')),
                ('content_type', models.ForeignKey(help_text='Type de responsable (Direction, SousDirection ou Service)', limit_choices_to={'model__in': ('direction', 'sousdirection', 'service')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('plan_action', models.ForeignKey(help_text="Plan d'action associé", on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='cartographie_risque.planaction')),
            ],
            options={
                'verbose_name': "Responsable Plan d'Action",
                'verbose_name_plural': "Responsables Plans d'Action",
                'db_table': 'plan_action_responsable',
                'ordering': ['plan_action', 'created_at'],
                'unique_together': {('plan_action', 'content_type', 'object_id')},
            },
        ),
    ]
