# Generated by Django 5.2.6 on 2025-11-18 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie_risque', '0007_alter_planaction_responsable_planactionresponsable'),
        ('parametre', '0040_statutactioncdr_actiontype_statuts_possibles'),
    ]

    operations = [
        # Étape 1 : Ajouter un nouveau champ ForeignKey temporaire
        migrations.AddField(
            model_name='suiviaction',
            name='statut_action_new',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='suivis_actions_new',
                to='parametre.statutactioncdr',
                help_text="Statut de l'action (nouveau modèle)"
            ),
        ),

        # Étape 2 : Supprimer l'ancien champ CharField
        migrations.RemoveField(
            model_name='suiviaction',
            name='statut_action',
        ),

        # Étape 3 : Renommer le nouveau champ
        migrations.RenameField(
            model_name='suiviaction',
            old_name='statut_action_new',
            new_name='statut_action',
        ),

        # Étape 4 : Mettre à jour le related_name
        migrations.AlterField(
            model_name='suiviaction',
            name='statut_action',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='suivis_actions',
                to='parametre.statutactioncdr',
                help_text="Statut de l'action"
            ),
        ),
    ]
