# Generated by Django 5.2.6 on 2025-11-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie_risque', '0008_migrate_statut_action_to_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdr',
            name='raison_amendement',
            field=models.TextField(blank=True, help_text='Raison ou cause de la création de cet amendement', null=True),
        ),
    ]
