# Generated by Django 4.2.26 on 2025-11-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie_risque', '0012_make_version_evaluation_required_and_add_unique_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationrisque',
            options={'ordering': ['details_cdr', 'version_evaluation__created_at', 'created_at'], 'verbose_name': 'Évaluation des Risques', 'verbose_name_plural': 'Évaluations des Risques'},
        ),
    ]
