# Generated by Django 6.0 on 2026-04-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie_risque', '0014_merge_20260409_0851'),
        ('parametre', '0057_userprocessusrole_is_global'),
    ]

    operations = [
        # 1. Vider l'ancien unique_together (qui référence type_tableau) avant de supprimer le champ
        migrations.AlterUniqueTogether(
            name='cdr',
            unique_together=set(),
        ),
        # 2. Supprimer l'ancien champ FK
        migrations.RemoveField(
            model_name='cdr',
            name='type_tableau',
        ),
        # 3. Ajouter le nouveau champ entier
        migrations.AddField(
            model_name='cdr',
            name='num_amendement',
            field=models.PositiveIntegerField(default=0, help_text='0 = CDR Initial, 1 = Amendement 1, N = Amendement N'),
        ),
        # 4. Créer le nouveau unique_together avec num_amendement
        migrations.AlterUniqueTogether(
            name='cdr',
            unique_together={('annee', 'processus', 'num_amendement')},
        ),
    ]
