# Generated by Django 4.2.26 on 2025-12-03 13:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametre', '0047_populate_mois_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nom du document', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description du document', null=True)),
                ('date_application', models.DateField(help_text="Date d'application du document")),
                ('is_active', models.BooleanField(default=True, help_text='Indique si ce document est actif et peut être utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee', models.ForeignKey(blank=True, help_text='Année associée au document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='parametre.annee')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'document',
                'ordering': ['-created_at'],
            },
        ),
    ]
