# Generated by Django 5.2.6 on 2026-04-02 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nom du document', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description du document', null=True)),
                ('date_application', models.DateField(help_text="Date d'application du document")),
                ('is_active', models.BooleanField(default=True, help_text='Indique si ce document est actif et peut être utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'document',
                'ordering': ['-created_at'],
            },
        ),
    ]
