# Generated by Django 5.2.6 on 2026-04-02 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentation', '0001_initial'),
        ('parametre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='amendement',
            field=models.ForeignKey(blank=True, help_text='Amendement associé au document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='parametre.amendementdocument'),
        ),
        migrations.AddField(
            model_name='document',
            name='edition',
            field=models.ForeignKey(blank=True, help_text='Édition associée au document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='parametre.editiondocument'),
        ),
        migrations.AddField(
            model_name='document',
            name='parent_document',
            field=models.ForeignKey(blank=True, help_text='Document parent pour le suivi des amendements', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='documentation.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Type de document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='parametre.typedocument'),
        ),
    ]
