# Generated by Django 4.2.26 on 2025-12-03 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0049_alter_amendementdocument_unique_together_and_more'),
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='amendement',
            field=models.ForeignKey(blank=True, help_text='Amendement associé au document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='parametre.amendementdocument'),
        ),
        migrations.AddField(
            model_name='document',
            name='edition',
            field=models.ForeignKey(blank=True, help_text='Édition associée au document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='parametre.editiondocument'),
        ),
    ]
