# Generated by Django 4.2.26 on 2025-12-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0050_categoriedocument'),
        ('documentation', '0002_document_amendement_document_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Catégories associées au document', related_name='documents', to='parametre.categoriedocument'),
        ),
    ]
