# Generated by Django 4.2.26 on 2025-12-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_add_parent_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='categories',
        ),
    ]
