# Generated by Django 4.2.26 on 2025-12-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0005_rename_categorie_to_type_document'),
        ('parametre', '0051_rename_categorie_to_type_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='types',
            field=models.ManyToManyField(blank=True, help_text='Types de documents associés', related_name='documents', to='parametre.typedocument'),
        ),
    ]
