# Generated by Django 4.2.26 on 2025-12-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0006_rename_categorie_to_type_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='annee',
        ),
    ]
