# Generated by Django 4.2.26 on 2025-12-09 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0051_rename_categorie_to_type_document'),
        ('documentation', '0007_remove_annee_from_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='types',
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Type de document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='parametre.typedocument'),
        ),
    ]
