# Generated by Django 5.2.6 on 2026-02-04 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0017_add_raison_amendement_to_tableaubord'),
        ('parametre', '0061_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseLigne',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objectif_non_atteint', models.TextField(help_text="Description de l'objectif non atteint")),
                ('cible', models.TextField(blank=True, help_text='Cible (texte libre)', null=True)),
                ('resultat', models.TextField(blank=True, help_text='Résultat constaté (texte libre)', null=True)),
                ('causes', models.TextField(blank=True, help_text="Causes de la non atteinte de l'objectif", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ligne d’analyse',
                'verbose_name_plural': 'Lignes d’analyse',
                'db_table': 'analyse_ligne',
            },
        ),
        migrations.CreateModel(
            name='AnalyseAction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.TextField(help_text="Description de l'action à mener")),
                ('delai_realisation', models.DateField(blank=True, help_text="Délai prévu pour la réalisation de l'action", null=True)),
                ('date_realisation', models.DateField(blank=True, help_text='Date effective de réalisation (si réalisée)', null=True)),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire complémentaire', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etat_mise_en_oeuvre', models.ForeignKey(blank=True, help_text="État de mise en œuvre de l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_actions', to='parametre.etatmiseenoeuvre')),
                ('evaluation', models.ForeignKey(blank=True, help_text="Évaluation de l'efficacité de l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_actions', to='parametre.appreciation')),
                ('preuve', models.ForeignKey(blank=True, help_text="Preuve(s) associée(s) à l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_actions', to='parametre.preuve')),
                ('responsables_directions', models.ManyToManyField(blank=True, help_text='Directions responsables de cette action', related_name='analyses_actions_responsables_directions', to='parametre.direction')),
                ('responsables_sous_directions', models.ManyToManyField(blank=True, help_text='Sous-directions responsables de cette action', related_name='analyses_actions_responsables_sous_directions', to='parametre.sousdirection')),
                ('ligne', models.ForeignKey(help_text="Ligne d'analyse (cause) associée", on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='analyse_tableau.analyseligne')),
            ],
            options={
                'verbose_name': "Action d'analyse",
                'verbose_name_plural': "Actions d'analyse",
                'db_table': 'analyse_action',
            },
        ),
        migrations.CreateModel(
            name='AnalyseTableau',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(help_text="Utilisateur qui a créé l'analyse", on_delete=django.db.models.deletion.CASCADE, related_name='analyses_tableau_creees', to=settings.AUTH_USER_MODEL)),
                ('tableau_bord', models.OneToOneField(help_text='Tableau de bord concerné par cette analyse', on_delete=django.db.models.deletion.CASCADE, related_name='analyse_tableau', to='dashboard.tableaubord')),
            ],
            options={
                'verbose_name': 'Analyse du tableau',
                'verbose_name_plural': 'Analyses des tableaux',
                'db_table': 'analyse_tableau',
            },
        ),
        migrations.AddField(
            model_name='analyseligne',
            name='analyse_tableau',
            field=models.ForeignKey(help_text='Analyse à laquelle appartient cette ligne', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='analyse_tableau.analysetableau'),
        ),
    ]
