# Generated by Django 5.2.6 on 2026-04-02 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseAction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.TextField(help_text="Description de l'action à mener")),
                ('delai_realisation', models.DateField(blank=True, help_text="Délai prévu pour la réalisation de l'action", null=True)),
                ('date_realisation', models.DateField(blank=True, help_text='Date effective de réalisation (si réalisée)', null=True)),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire complémentaire', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Action d'analyse",
                'verbose_name_plural': "Actions d'analyse",
                'db_table': 'analyse_action',
            },
        ),
        migrations.CreateModel(
            name='AnalyseLigne',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode', models.CharField(blank=True, choices=[('T1', '1er Trimestre'), ('T2', '2ème Trimestre'), ('T3', '3ème Trimestre'), ('T4', '4ème Trimestre'), ('S1', '1er Semestre'), ('S2', '2ème Semestre'), ('A1', 'Année')], help_text="Trimestre / période de l'analyse (T1, T2, ...)", max_length=10, null=True)),
                ('objectif_non_atteint', models.TextField(help_text="Description de l'objectif non atteint")),
                ('cible', models.TextField(blank=True, help_text='Cible (texte libre)', null=True)),
                ('resultat', models.TextField(blank=True, help_text='Résultat constaté (texte libre)', null=True)),
                ('causes', models.TextField(blank=True, help_text="Causes de la non atteinte de l'objectif", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Ligne d'analyse",
                'verbose_name_plural': "Lignes d'analyse",
                'db_table': 'analyse_ligne',
            },
        ),
        migrations.CreateModel(
            name='AnalyseTableau',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analyse du tableau',
                'verbose_name_plural': 'Analyses des tableaux',
                'db_table': 'analyse_tableau',
            },
        ),
    ]
