# Generated by Django 5.2.6 on 2026-04-02 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyse_tableau', '0001_initial'),
        ('dashboard', '0001_initial'),
        ('parametre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyseaction',
            name='etat_mise_en_oeuvre',
            field=models.ForeignKey(blank=True, help_text="État de mise en œuvre de l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_actions', to='parametre.etatmiseenoeuvre'),
        ),
        migrations.AddField(
            model_name='analyseaction',
            name='evaluation',
            field=models.ForeignKey(blank=True, help_text="Évaluation de l'efficacité de l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_actions', to='parametre.appreciation'),
        ),
        migrations.AddField(
            model_name='analyseaction',
            name='preuve',
            field=models.ForeignKey(blank=True, help_text="Preuve(s) associée(s) à l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_actions', to='parametre.preuve'),
        ),
        migrations.AddField(
            model_name='analyseaction',
            name='responsables_directions',
            field=models.ManyToManyField(blank=True, help_text='Directions responsables de cette action', related_name='analyses_actions_responsables_directions', to='parametre.direction'),
        ),
        migrations.AddField(
            model_name='analyseaction',
            name='responsables_sous_directions',
            field=models.ManyToManyField(blank=True, help_text='Sous-directions responsables de cette action', related_name='analyses_actions_responsables_sous_directions', to='parametre.sousdirection'),
        ),
        migrations.AddField(
            model_name='analyseaction',
            name='ligne',
            field=models.ForeignKey(help_text="Ligne d'analyse (cause) associée", on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='analyse_tableau.analyseligne'),
        ),
        migrations.AddField(
            model_name='analysetableau',
            name='cree_par',
            field=models.ForeignKey(help_text="Utilisateur qui a créé l'analyse", on_delete=django.db.models.deletion.CASCADE, related_name='analyses_tableau_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysetableau',
            name='tableau_bord',
            field=models.OneToOneField(help_text='Tableau de bord concerné par cette analyse', on_delete=django.db.models.deletion.CASCADE, related_name='analyse_tableau', to='dashboard.tableaubord'),
        ),
        migrations.AddField(
            model_name='analyseligne',
            name='analyse_tableau',
            field=models.ForeignKey(help_text='Analyse à laquelle appartient cette ligne', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='analyse_tableau.analysetableau'),
        ),
        migrations.AddConstraint(
            model_name='analyseligne',
            constraint=models.UniqueConstraint(fields=('analyse_tableau', 'periode'), name='unique_ligne_per_analyse_tableau_periode'),
        ),
    ]
