# Generated by Django 6.0 on 2026-02-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_tableau', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyseligne',
            name='periode',
            field=models.CharField(blank=True, choices=[('T1', '1er Trimestre'), ('T2', '2ème Trimestre'), ('T3', '3ème Trimestre'), ('T4', '4ème Trimestre'), ('S1', '1er Semestre'), ('S2', '2ème Semestre'), ('A1', 'Année')], help_text="Trimestre / période de l'analyse (T1, T2, ...)", max_length=10, null=True),
        ),
    ]
