# Generated by Django 6.0 on 2026-02-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_tableau', '0002_analyseligne_periode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyseligne',
            options={'verbose_name': "Ligne d'analyse", 'verbose_name_plural': "Lignes d'analyse"},
        ),
        migrations.AddConstraint(
            model_name='analyseligne',
            constraint=models.UniqueConstraint(fields=('analyse_tableau', 'periode'), name='unique_ligne_per_analyse_tableau_periode'),
        ),
    ]
