# Generated by Django 4.2.26 on 2025-11-29 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametre', '0045_alter_versionevaluationcdr_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitePeriodique',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_validated', models.BooleanField(default=False, help_text='Indique que tous les détails et périodicités sont renseignés.')),
                ('validated_at', models.DateTimeField(blank=True, help_text='Date de validation des détails et périodicités', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee', models.ForeignKey(blank=True, help_text="Année associée à l'activité périodique", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_periodiques', to='parametre.annee')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_periodiques_crees', to=settings.AUTH_USER_MODEL)),
                ('initial_ref', models.ForeignKey(blank=True, help_text="Référence à l'activité périodique initiale (pour les amendements)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amendements', to='activite_periodique.activiteperiodique')),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_periodiques', to='parametre.processus')),
                ('type_tableau', models.ForeignKey(blank=True, help_text="Version associée à l'activité périodique (Initial, Amendement, etc.)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_periodiques', to='parametre.versions')),
                ('validated_by', models.ForeignKey(blank=True, help_text="Utilisateur qui a validé l'activité périodique", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_periodiques_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité Périodique',
                'verbose_name_plural': 'Activités Périodiques',
                'db_table': 'activite_periodique',
            },
        ),
        migrations.CreateModel(
            name='DetailsAP',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_ap', models.CharField(blank=True, help_text='Numéro du détail Activité Périodique', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activite_periodique', models.ForeignKey(help_text='Activité Périodique associée', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='activite_periodique.activiteperiodique')),
                ('responsabilite_direction', models.ForeignKey(blank=True, help_text='Direction responsable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details_ap_responsables', to='parametre.direction')),
                ('responsabilite_service', models.ForeignKey(blank=True, help_text='Service responsable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details_ap_responsables', to='parametre.service')),
                ('responsabilite_sous_direction', models.ForeignKey(blank=True, help_text='Sous-direction responsable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details_ap_responsables', to='parametre.sousdirection')),
                ('responsables_directions', models.ManyToManyField(blank=True, related_name='details_ap_responsables_m2m', to='parametre.direction')),
                ('responsables_services', models.ManyToManyField(blank=True, related_name='details_ap_responsables_services_m2m', to='parametre.service')),
                ('responsables_sous_directions', models.ManyToManyField(blank=True, related_name='details_ap_responsables_sous_m2m', to='parametre.sousdirection')),
            ],
            options={
                'verbose_name': 'Détail Activité Périodique',
                'verbose_name_plural': 'Détails Activités Périodiques',
                'db_table': 'details_ap',
            },
        ),
        migrations.CreateModel(
            name='PeriodiciteAP',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode', models.CharField(choices=[('T1', '1er Trimestre'), ('T2', '2ème Trimestre'), ('T3', '3ème Trimestre'), ('T4', '4ème Trimestre')], help_text='Période trimestrielle', max_length=2)),
                ('livrable', models.TextField(help_text="Description du livrable (ex: Rapport d'activités 1er trimestre 2024)")),
                ('date_realisation', models.DateField(blank=True, help_text='Date prévue de réalisation du livrable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details_ap', models.ForeignKey(help_text='Détail Activité Périodique associé', on_delete=django.db.models.deletion.CASCADE, related_name='periodicites', to='activite_periodique.detailsap')),
            ],
            options={
                'verbose_name': 'Périodicité Activité Périodique',
                'verbose_name_plural': 'Périodicités Activités Périodiques',
                'db_table': 'periodicite_ap',
                'ordering': ['details_ap', 'periode'],
                'unique_together': {('details_ap', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='MoisAP',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mois', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], help_text='Numéro du mois (1-12)')),
                ('trimestre', models.CharField(choices=[('T1', '1er Trimestre'), ('T2', '2ème Trimestre'), ('T3', '3ème Trimestre'), ('T4', '4ème Trimestre')], help_text='Trimestre auquel appartient ce mois', max_length=2)),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etat_mise_en_oeuvre', models.ForeignKey(blank=True, help_text='État de mise en œuvre pour ce mois', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mois_ap', to='parametre.etatmiseenoeuvre')),
                ('periodicite_ap', models.ForeignKey(help_text='Périodicité Activité Périodique associée', on_delete=django.db.models.deletion.CASCADE, related_name='mois', to='activite_periodique.periodiciteap')),
            ],
            options={
                'verbose_name': 'Mois Activité Périodique',
                'verbose_name_plural': 'Mois Activités Périodiques',
                'db_table': 'mois_ap',
                'ordering': ['periodicite_ap', 'mois'],
                'unique_together': {('periodicite_ap', 'mois')},
            },
        ),
        migrations.AddConstraint(
            model_name='activiteperiodique',
            constraint=models.UniqueConstraint(fields=('processus', 'annee', 'type_tableau', 'cree_par'), name='unique_activite_periodique_per_processus_annee_type_tableau_user'),
        ),
    ]
