# Generated by Django 5.2.6 on 2026-04-02 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitePeriodique',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_validated', models.BooleanField(default=False, help_text='Indique que tous les détails et périodicités sont renseignés.')),
                ('validated_at', models.DateTimeField(blank=True, help_text='Date de validation des détails et périodicités', null=True)),
                ('raison_amendement', models.TextField(blank=True, help_text='Raison ou cause de la création de cet amendement', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activité Périodique',
                'verbose_name_plural': 'Activités Périodiques',
                'db_table': 'activite_periodique',
            },
        ),
        migrations.CreateModel(
            name='DetailsAP',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_ap', models.CharField(blank=True, help_text='Numéro du détail Activité Périodique', max_length=50, null=True)),
                ('activites_periodiques', models.TextField(blank=True, help_text='Description des activités périodiques', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Détail Activité Périodique',
                'verbose_name_plural': 'Détails Activités Périodiques',
                'db_table': 'details_ap',
            },
        ),
        migrations.CreateModel(
            name='SuivisAP',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('livrable', models.TextField(blank=True, help_text='Livrable associé à ce suivi', null=True)),
                ('date_realisation', models.DateField(blank=True, help_text='Date de réalisation effective', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Suivi AP',
                'verbose_name_plural': 'Suivis AP',
                'db_table': 'suivis_ap',
                'ordering': ['details_ap', 'mois__numero'],
            },
        ),
    ]
