# Generated by Django 4.2.26 on 2025-12-02 05:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


def migrate_moisap_to_suivisap(apps, schema_editor):
    """Migrate data from MoisAP to SuivisAP"""
    MoisAP = apps.get_model('activite_periodique', 'MoisAP')
    SuivisAP = apps.get_model('activite_periodique', 'SuivisAP')
    Mois = apps.get_model('parametre', 'Mois')
    Frequence = apps.get_model('parametre', 'Frequence')
    
    # Mapping des mois
    mois_mapping = {
        1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
        5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
        9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
    }
    
    # Mapping des trimestres vers fréquences
    trimestre_to_frequence = {
        'T1': 'Trimestrielle',
        'T2': 'Trimestrielle',
        'T3': 'Trimestrielle',
        'T4': 'Trimestrielle',
    }
    
    # Migrer chaque MoisAP vers SuivisAP
    for mois_ap in MoisAP.objects.all():
        # Trouver le mois correspondant
        try:
            mois_obj = Mois.objects.get(numero=mois_ap.mois)
        except Mois.DoesNotExist:
            # Si le mois n'existe pas, le créer
            mois_nom = mois_mapping.get(mois_ap.mois, f'Mois {mois_ap.mois}')
            mois_obj = Mois.objects.create(
                numero=mois_ap.mois,
                nom=mois_nom,
                abreviation=mois_nom[0] if mois_nom else 'M'
            )
        
        # Trouver la fréquence correspondante
        frequence_nom = trimestre_to_frequence.get(mois_ap.trimestre, 'Trimestrielle')
        try:
            frequence_obj = Frequence.objects.get(nom=frequence_nom)
        except Frequence.DoesNotExist:
            # Si la fréquence n'existe pas, la créer
            frequence_obj = Frequence.objects.create(nom=frequence_nom)
        
        # Créer le SuivisAP
        SuivisAP.objects.create(
            uuid=mois_ap.uuid,
            periodicite_ap=mois_ap.periodicite_ap,
            mois=mois_obj,
            frequence=frequence_obj,
            etat_mise_en_oeuvre=mois_ap.etat_mise_en_oeuvre,
            commentaire=None,  # Ancien modèle n'avait pas de commentaire
            is_active=mois_ap.is_active,
            created_at=mois_ap.created_at,
            updated_at=mois_ap.updated_at
        )


def reverse_migrate(apps, schema_editor):
    """Reverse migration - not implemented as data loss would occur"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0047_populate_mois_data'),
        ('activite_periodique', '0001_initial'),
    ]

    operations = [
        # Créer le nouveau modèle SuivisAP
        migrations.CreateModel(
            name='SuivisAP',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire sur le suivi', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet élément est actif et peut être utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etat_mise_en_oeuvre', models.ForeignKey(blank=True, help_text='État de mise en œuvre pour ce suivi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis_ap', to='parametre.etatmiseenoeuvre')),
                ('frequence', models.ForeignKey(help_text='Fréquence associée (Trimestrielle, Semestrielle, Annuelle, Mensuelle, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='suivis_ap', to='parametre.frequence')),
                ('mois', models.ForeignKey(help_text='Mois de référence', on_delete=django.db.models.deletion.CASCADE, related_name='suivis_ap', to='parametre.mois')),
                ('periodicite_ap', models.ForeignKey(help_text='Périodicité Activité Périodique associée', on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='activite_periodique.periodiciteap')),
            ],
            options={
                'verbose_name': 'Suivi AP',
                'verbose_name_plural': 'Suivis AP',
                'db_table': 'suivis_ap',
                'ordering': ['periodicite_ap', 'mois__numero'],
                'unique_together': {('periodicite_ap', 'mois')},
            },
        ),
        # Migrer les données
        migrations.RunPython(migrate_moisap_to_suivisap, reverse_migrate),
        # Supprimer l'ancien modèle
        migrations.DeleteModel(
            name='MoisAP',
        ),
    ]
