# Generated by Django 5.2.6 on 2026-04-02 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activite_periodique', '0001_initial'),
        ('parametre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activiteperiodique',
            name='annee',
            field=models.ForeignKey(blank=True, help_text="Année associée à l'activité périodique", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_periodiques', to='parametre.annee'),
        ),
        migrations.AddField(
            model_name='activiteperiodique',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_periodiques_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activiteperiodique',
            name='initial_ref',
            field=models.ForeignKey(blank=True, help_text="Référence à l'activité périodique initiale (pour les amendements)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amendements', to='activite_periodique.activiteperiodique'),
        ),
        migrations.AddField(
            model_name='activiteperiodique',
            name='processus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_periodiques', to='parametre.processus'),
        ),
        migrations.AddField(
            model_name='activiteperiodique',
            name='type_tableau',
            field=models.ForeignKey(blank=True, help_text="Version associée à l'activité périodique (Initial, Amendement, etc.)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_periodiques', to='parametre.versions'),
        ),
        migrations.AddField(
            model_name='activiteperiodique',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text="Utilisateur qui a validé l'activité périodique", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_periodiques_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detailsap',
            name='activite_periodique',
            field=models.ForeignKey(help_text='Activité Périodique associée', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='activite_periodique.activiteperiodique'),
        ),
        migrations.AddField(
            model_name='detailsap',
            name='frequence',
            field=models.ForeignKey(blank=True, help_text='Fréquence associée (Trimestrielle, Semestrielle, Annuelle, Mensuelle, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details_ap', to='parametre.frequence'),
        ),
        migrations.AddField(
            model_name='detailsap',
            name='responsabilite_direction',
            field=models.ForeignKey(blank=True, help_text='Direction responsable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details_ap_responsables', to='parametre.direction'),
        ),
        migrations.AddField(
            model_name='detailsap',
            name='responsabilite_service',
            field=models.ForeignKey(blank=True, help_text='Service responsable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details_ap_responsables', to='parametre.service'),
        ),
        migrations.AddField(
            model_name='detailsap',
            name='responsabilite_sous_direction',
            field=models.ForeignKey(blank=True, help_text='Sous-direction responsable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details_ap_responsables', to='parametre.sousdirection'),
        ),
        migrations.AddField(
            model_name='detailsap',
            name='responsables_directions',
            field=models.ManyToManyField(blank=True, related_name='details_ap_responsables_m2m', to='parametre.direction'),
        ),
        migrations.AddField(
            model_name='detailsap',
            name='responsables_services',
            field=models.ManyToManyField(blank=True, related_name='details_ap_responsables_services_m2m', to='parametre.service'),
        ),
        migrations.AddField(
            model_name='detailsap',
            name='responsables_sous_directions',
            field=models.ManyToManyField(blank=True, related_name='details_ap_responsables_sous_m2m', to='parametre.sousdirection'),
        ),
        migrations.AddField(
            model_name='suivisap',
            name='details_ap',
            field=models.ForeignKey(help_text='Détail Activité Périodique associé', on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='activite_periodique.detailsap'),
        ),
        migrations.AddField(
            model_name='suivisap',
            name='etat_mise_en_oeuvre',
            field=models.ForeignKey(blank=True, help_text='État de mise en œuvre pour ce mois (Réalisée, Non réalisée, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis_ap', to='parametre.etatmiseenoeuvre'),
        ),
        migrations.AddField(
            model_name='suivisap',
            name='mois',
            field=models.ForeignKey(help_text='Mois de référence', on_delete=django.db.models.deletion.CASCADE, related_name='suivis_ap', to='parametre.mois'),
        ),
        migrations.AddConstraint(
            model_name='activiteperiodique',
            constraint=models.UniqueConstraint(fields=('processus', 'annee', 'type_tableau', 'cree_par'), name='unique_activite_periodique_per_processus_annee_type_tableau_user'),
        ),
        migrations.AlterUniqueTogether(
            name='suivisap',
            unique_together={('details_ap', 'mois')},
        ),
    ]
