# Generated by Django 4.2.26 on 2025-12-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activite_periodique', '0002_rename_moisap_to_suivisap'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoisAP',
            fields=[
            ],
            options={
                'verbose_name': 'Mois Activité Périodique',
                'verbose_name_plural': 'Mois Activités Périodiques',
                'db_table': 'suivis_ap',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('activite_periodique.suivisap',),
        ),
    ]
