# Generated by Django 4.2.26 on 2025-12-02 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0047_populate_mois_data'),
        ('activite_periodique', '0003_add_moisap_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsap',
            name='activites_periodiques',
            field=models.TextField(blank=True, help_text='Description des activités périodiques', null=True),
        ),
        migrations.AddField(
            model_name='detailsap',
            name='frequence',
            field=models.ForeignKey(blank=True, help_text='Fréquence associée (Trimestrielle, Semestrielle, Annuelle, Mensuelle, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details_ap', to='parametre.frequence'),
        ),
    ]
