# Generated by Django 4.2.26 on 2025-12-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activite_periodique', '0004_add_activites_periodiques_and_frequence_to_detailsap'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='periodiciteap',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='periodiciteap',
            name='details_ap',
        ),
        migrations.AlterUniqueTogether(
            name='suivisap',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='suivisap',
            name='etat_mise_en_oeuvre',
        ),
        migrations.RemoveField(
            model_name='suivisap',
            name='frequence',
        ),
        migrations.RemoveField(
            model_name='suivisap',
            name='mois',
        ),
        migrations.RemoveField(
            model_name='suivisap',
            name='periodicite_ap',
        ),
        migrations.DeleteModel(
            name='MoisAP',
        ),
        migrations.DeleteModel(
            name='PeriodiciteAP',
        ),
        migrations.DeleteModel(
            name='SuivisAP',
        ),
    ]
