# Generated by Django 4.2.26 on 2025-12-02 07:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0047_populate_mois_data'),
        ('activite_periodique', '0005_remove_periodicite_and_suivis_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuivisAP',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire sur le suivi de ce mois', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details_ap', models.ForeignKey(help_text='Détail Activité Périodique associé', on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='activite_periodique.detailsap')),
                ('etat_mise_en_oeuvre', models.ForeignKey(blank=True, help_text='État de mise en œuvre pour ce mois (Réalisée, Non réalisée, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis_ap', to='parametre.etatmiseenoeuvre')),
                ('mois', models.ForeignKey(help_text='Mois de référence', on_delete=django.db.models.deletion.CASCADE, related_name='suivis_ap', to='parametre.mois')),
            ],
            options={
                'verbose_name': 'Suivi AP',
                'verbose_name_plural': 'Suivis AP',
                'db_table': 'suivis_ap',
                'ordering': ['details_ap', 'mois__numero'],
                'unique_together': {('details_ap', 'mois')},
            },
        ),
    ]
