# Generated by Django 4.2.26 on 2025-12-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activite_periodique', '0006_create_suivisap_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suivisap',
            name='commentaire',
        ),
    ]
