# Generated by Django 6.0 on 2026-03-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite_periodique', '0008_add_livrable_and_date_realisation_to_suivisap'),
    ]

    operations = [
        migrations.AddField(
            model_name='activiteperiodique',
            name='raison_amendement',
            field=models.TextField(blank=True, help_text='Raison ou cause de la création de cet amendement', null=True),
        ),
    ]
