# Generated by Django 6.0 on 2026-04-16 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite_periodique', '0009_merge_20260409_0851'),
        ('parametre', '0057_userprocessusrole_is_global'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activiteperiodique',
            name='unique_activite_periodique_per_processus_annee_type_tableau_user',
        ),
        migrations.AddField(
            model_name='activiteperiodique',
            name='num_amendement',
            field=models.PositiveIntegerField(default=0, help_text='0 = Activité Initiale, 1 = Amendement 1, N = Amendement N'),
        ),
        migrations.AddConstraint(
            model_name='activiteperiodique',
            constraint=models.UniqueConstraint(fields=('processus', 'annee', 'num_amendement', 'cree_par'), name='unique_activite_periodique_per_processus_annee_num_amendement_user'),
        ),
        migrations.RemoveField(
            model_name='activiteperiodique',
            name='type_tableau',
        ),
    ]
